local ScreenGui = Instance.new("ScreenGui")
local Gui = Instance.new("ImageLabel")
local ScrollingFrame = Instance.new("ScrollingFrame")
local Speed = Instance.new("TextButton")
local TextButton_Roundify_12px = Instance.new("ImageLabel")
local HighJump = Instance.new("TextButton")
local TextButton_Roundify_12px_2 = Instance.new("ImageLabel")
local TextLabel = Instance.new("TextLabel")
local TextLabel_Roundify_12px = Instance.new("ImageLabel")
local SpeedFrame = Instance.new("ImageLabel")
local SpeedModification = Instance.new("TextLabel")
local TextLabel_Roundify_12px_2 = Instance.new("ImageLabel")
local SpeedBox = Instance.new("TextBox")
local TextBox_Roundify_12px = Instance.new("ImageLabel")
local somethignspeed = Instance.new("TextLabel")
local Ok = Instance.new("TextButton")
local TextButton_Roundify_12px_3 = Instance.new("ImageLabel")
local HighJumpFrame = Instance.new("ImageLabel")
local HighJumpModification = Instance.new("TextLabel")
local TextLabel_Roundify_12px_3 = Instance.new("ImageLabel")
local JumpBox = Instance.new("TextBox")
local TextBox_Roundify_12px_2 = Instance.new("ImageLabel")
local somethignjump = Instance.new("TextLabel")
local Ok_2 = Instance.new("TextButton")
local TextButton_Roundify_12px_4 = Instance.new("ImageLabel")
local InfJumpFrame = Instance.new("ImageLabel")
local InfJumpModification = Instance.new("TextLabel")
local socaughtonma = Instance.new("ImageLabel")
local InfBox = Instance.new("TextBox")
local ify = Instance.new("ImageLabel")
local somethigninf = Instance.new("TextLabel")
local OkInfJump = Instance.new("TextButton")
local round = Instance.new("ImageLabel")
local InfJump = Instance.new("TextButton")
local TextButton_Roundify_12px_9 = Instance.new("ImageLabel")
local disabled = Instance.new("TextButton")
local omgitsgabry = Instance.new("ImageLabel")
local disabled1 = Instance.new("TextButton")
local omgitsgabry1 = Instance.new("ImageLabel")
local disabled2 = Instance.new("TextButton")
local omgitsgabry2 = Instance.new("ImageLabel")
local GameTPFrame = Instance.new("ImageLabel")
local Title = Instance.new("TextLabel")
local socaughtonma = Instance.new("ImageLabel")
local Jailbreak = Instance.new("TextButton")
local jail = Instance.new("ImageLabel")
local Prisonlife = Instance.new("TextButton")
local prison = Instance.new("ImageLabel")
local AdoptMe = Instance.new("TextButton")
local adopt = Instance.new("ImageLabel")
local Plsdonate = Instance.new("TextButton")
local pls = Instance.new("ImageLabel")
local GameTeleport = Instance.new("TextButton")
local ezz = Instance.new("ImageLabel")
local madeby = Instance.new("TextLabel")
local Title_Roundify_12px = Instance.new("ImageLabel")
local Invisibility = Instance.new("TextButton")
local TextButton_Roundify_12px_0 = Instance.new("ImageLabel")
local InvisibilityFrame = Instance.new("ImageLabel")
local disabled7 = Instance.new("TextButton")
local omgitsgabry7 = Instance.new("ImageLabel")
local InvisibilityMod = Instance.new("TextLabel")
local modround = Instance.new("ImageLabel")
local invisok = Instance.new("TextButton")
local invisround = Instance.new("ImageLabel")
local Esp = Instance.new("TextButton")
local espround = Instance.new("ImageLabel")
local EspFrame = Instance.new("ImageLabel")
local disabled71 = Instance.new("TextButton")
local omgitsgabry21 = Instance.new("ImageLabel")
local espmod = Instance.new("TextLabel")
local espmodround = Instance.new("ImageLabel")
local espok = Instance.new("TextButton")
local espokround = Instance.new("ImageLabel")
local GameChecker = Instance.new("TextLabel")
local ScriptsFrame = Instance.new("ImageLabel")
local othscriptitle = Instance.new("TextLabel")
local othscrround = Instance.new("ImageLabel")
local OwlHub = Instance.new("TextButton")
local owl = Instance.new("ImageLabel")
local Ivadmin = Instance.new("TextButton")
local iv = Instance.new("ImageLabel")
local InfYield = Instance.new("TextButton")
local inf = Instance.new("ImageLabel")
local OtherScripts = Instance.new("TextButton")
local scriptround = Instance.new("ImageLabel")
local AimFrame = Instance.new("ImageLabel")
local aimdisabled = Instance.new("TextButton")
local aimdisround = Instance.new("ImageLabel")
local aimmod = Instance.new("TextLabel")
local aimmodround = Instance.new("ImageLabel")
local aimok = Instance.new("TextButton")
local aimokround = Instance.new("ImageLabel")
local AimBot = Instance.new("TextButton")
local aimround = Instance.new("ImageLabel")
local Spectate = Instance.new("TextButton")
local specround = Instance.new("ImageLabel")
local SpectateFrame = Instance.new("ImageLabel")
local specdisable = Instance.new("TextButton")
local specdisableround = Instance.new("ImageLabel")
local SpecMod = Instance.new("TextLabel")
local specmodorund = Instance.new("ImageLabel")
local specplayerbox = Instance.new("TextBox")
local specplayerboxround = Instance.new("ImageLabel")
local somthspec = Instance.new("TextLabel")
local specok = Instance.new("TextButton")
local specokround = Instance.new("ImageLabel")
local teamcheck = Instance.new("TextButton")
local teamcheckdis = Instance.new("ImageLabel")
local teamcheckdis_2 = Instance.new("TextButton")
local teamcheckdisround = Instance.new("ImageLabel")
local hub = Instance.new("TextLabel")
local hubround = Instance.new("ImageLabel")
local Animations = Instance.new("TextButton")
local animround = Instance.new("ImageLabel")
local AnimationsFrame = Instance.new("ImageLabel")
local Animations_2 = Instance.new("TextLabel")
local othscrround = Instance.new("ImageLabel")
local Float = Instance.new("TextButton")
local floatround = Instance.new("ImageLabel")
local anim3 = Instance.new("TextButton")
local anim3round = Instance.new("ImageLabel")
local BigPP = Instance.new("TextButton")
local pp = Instance.new("ImageLabel")
local Notification = Instance.new("ImageLabel")
local TextLabel_55 = Instance.new("TextLabel")
local TextLabel_2 = Instance.new("TextLabel")
local notifround = Instance.new("ImageLabel")
local CodeFrame = Instance.new("ImageLabel")
local codelabel1 = Instance.new("TextLabel")
local codelabelround = Instance.new("ImageLabel")
local CodeBox = Instance.new("TextBox")
local coderound = Instance.new("ImageLabel")
local codelabel2 = Instance.new("TextLabel")
local okcode = Instance.new("TextButton")
local codeokround = Instance.new("ImageLabel")

local TPservice = game:GetService("TeleportService")

--Properties:

local codes = {"9V4J9Ud1Cv3","4m1dt5s0SC7","7KtH788VN6T","65y7S0Tcr0b","K880iM06oTi","Nbt10G9n54t","2i7Pvl23q4l","8nk6AWb2V66","KLq41Y3h3U6","rgCa952a6e4","z414NM6HbH6","8V2Oo3S98Yg","7Hha6g28a0e","71AI14qh8gt","L5rqM498z9Y","jY20i4Nl96g","3RP6ttg195i","p67uAb73s2V","pEQ89v70m9N","B63GAk69yX9"}

ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ScreenGui.DisplayOrder = 5
ScreenGui.ResetOnSpawn = false

Gui.Name = "Gui"
Gui.Parent = ScreenGui
Gui.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Gui.BackgroundTransparency = 1.000
Gui.Position = UDim2.new(0.35578689, 0, 0.28447026, 0)
Gui.Size = UDim2.new(0, 690,0, 412)
Gui.Visible = false
Gui.Image = "rbxassetid://3570695787"
Gui.ImageColor3 = Color3.fromRGB(79, 79, 79)
Gui.ScaleType = Enum.ScaleType.Slice
Gui.SliceCenter = Rect.new(100, 100, 100, 100)
Gui.SliceScale = 0.120

Notification.Name = "Notification"
Notification.Parent = ScreenGui
Notification.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Notification.BackgroundTransparency = 1.000
Notification.Position = UDim2.new(0.863210499, 0, 0.870370388, 0)
Notification.Size = UDim2.new(0, 213, 0, 99)
Notification.Visible = false
Notification.Image = "rbxassetid://3570695787"
Notification.ImageColor3 = Color3.fromRGB(71, 71, 71)
Notification.ImageTransparency = 0.200
Notification.ScaleType = Enum.ScaleType.Slice
Notification.SliceCenter = Rect.new(100, 100, 100, 100)
Notification.SliceScale = 0.120

TextLabel_55.Parent = Notification
TextLabel_55.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_55.BackgroundTransparency = 1.000
TextLabel_55.BorderSizePixel = 0
TextLabel_55.Size = UDim2.new(0, 213, 0, 50)
TextLabel_55.Font = Enum.Font.Gotham
TextLabel_55.Text = "Loaded!"
TextLabel_55.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_55.TextSize = 20.000
TextLabel_55.TextWrapped = true
TextLabel_55.ZIndex = 2
TextLabel_2.Parent = Notification
TextLabel_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_2.BackgroundTransparency = 1.000
TextLabel_2.BorderSizePixel = 0
TextLabel_2.Position = UDim2.new(0, 0, 0.49494949, 0)
TextLabel_2.Size = UDim2.new(0, 213, 0, 36)
TextLabel_2.Font = Enum.Font.Gotham
TextLabel_2.Text = "Succesfully loaded {}"
TextLabel_2.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_2.TextSize = 13.000
TextLabel_2.TextWrapped = true
TextLabel_2.ZIndex = 2
notifround.Name = "notifround"
notifround.Parent = TextLabel_55
notifround.AnchorPoint = Vector2.new(0.5, 0.5)
notifround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
notifround.BackgroundTransparency = 1.000
notifround.Position = UDim2.new(0.5, 0, 0.5, 0)
notifround.Size = UDim2.new(1, 0, 1, 0)
notifround.Image = "rbxassetid://3570695787"
notifround.ImageColor3 = Color3.fromRGB(62, 62, 62)
notifround.ImageTransparency = 0.200
notifround.ScaleType = Enum.ScaleType.Slice
notifround.SliceCenter = Rect.new(100, 100, 100, 100)
notifround.SliceScale = 0.120
local player = game.Players.LocalPlayer
local mouse = player:GetMouse()

CodeFrame.Name = "CodeFrame"
CodeFrame.Parent = ScreenGui
CodeFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CodeFrame.BackgroundTransparency = 1.000
CodeFrame.Position = UDim2.new(0.401623964, 0, 0.237037033, 0)
CodeFrame.Size = UDim2.new(0, 690, 0, 412)
CodeFrame.Image = "rbxassetid://3570695787"
CodeFrame.ImageColor3 = Color3.fromRGB(79, 79, 79)
CodeFrame.ScaleType = Enum.ScaleType.Slice
CodeFrame.SliceCenter = Rect.new(100, 100, 100, 100)
CodeFrame.SliceScale = 0.120

codelabel1.Name = "codelabel1"
codelabel1.Parent = CodeFrame
codelabel1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
codelabel1.BackgroundTransparency = 1.000
codelabel1.BorderSizePixel = 0
codelabel1.Size = UDim2.new(0, 690, 0, 66)
codelabel1.ZIndex = 2
codelabel1.Font = Enum.Font.Gotham
codelabel1.Text = "   Mercury v2"
codelabel1.TextColor3 = Color3.fromRGB(0, 86, 255)
codelabel1.TextSize = 35.000
codelabel1.TextXAlignment = Enum.TextXAlignment.Left

codelabelround.Name = "codelabelround"
codelabelround.Parent = codelabel1
codelabelround.AnchorPoint = Vector2.new(0.5, 0.5)
codelabelround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
codelabelround.BackgroundTransparency = 1.000
codelabelround.Position = UDim2.new(0.5, 0, 0.5, 0)
codelabelround.Size = UDim2.new(1, 0, 1, 0)
codelabelround.Image = "rbxassetid://3570695787"
codelabelround.ImageColor3 = Color3.fromRGB(66, 66, 66)
codelabelround.ScaleType = Enum.ScaleType.Slice
codelabelround.SliceCenter = Rect.new(100, 100, 100, 100)
codelabelround.SliceScale = 0.120

CodeBox.Name = "CodeBox"
CodeBox.Parent = CodeFrame
CodeBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CodeBox.BackgroundTransparency = 1.000
CodeBox.BorderSizePixel = 0
CodeBox.Position = UDim2.new(0.136855409, 0, 0.436893195, 0)
CodeBox.Size = UDim2.new(0, 507, 0, 50)
CodeBox.ZIndex = 4
CodeBox.Font = Enum.Font.Gotham
CodeBox.Text = ""
CodeBox.TextColor3 = Color3.fromRGB(255, 255, 255)
CodeBox.TextSize = 14.000

coderound.Name = "coderound"
coderound.Parent = CodeBox
coderound.Active = true
coderound.AnchorPoint = Vector2.new(0.5, 0.5)
coderound.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
coderound.BackgroundTransparency = 1.000
coderound.Position = UDim2.new(0.49735263, 0, 0.510314941, 0)
coderound.Selectable = true
coderound.Size = UDim2.new(0.950701654, 0, 0.867692232, 0)
coderound.ZIndex = 3
coderound.Image = "rbxassetid://3570695787"
coderound.ImageColor3 = Color3.fromRGB(107, 107, 107)
coderound.ScaleType = Enum.ScaleType.Slice
coderound.SliceCenter = Rect.new(100, 100, 100, 100)
coderound.SliceScale = 0.120

codelabel2.Name = "codelabel2"
codelabel2.Parent = CodeFrame
codelabel2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
codelabel2.BackgroundTransparency = 1.000
codelabel2.BorderSizePixel = 0
codelabel2.Position = UDim2.new(0.366666675, 0, 0.330097079, 0)
codelabel2.Size = UDim2.new(0, 182, 0, 44)
codelabel2.ZIndex = 2
codelabel2.Font = Enum.Font.Gotham
codelabel2.Text = "Enter your code"
codelabel2.TextColor3 = Color3.fromRGB(0, 86, 255)
codelabel2.TextSize = 25.000
codelabel2.TextXAlignment = Enum.TextXAlignment.Left

okcode.Name = "okcode"
okcode.Parent = CodeFrame
okcode.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
okcode.BackgroundTransparency = 1.000
okcode.BorderSizePixel = 0
okcode.Position = UDim2.new(0.421892077, 0, 0.590863585, 0)
okcode.Size = UDim2.new(0, 104, 0, 34)
okcode.ZIndex = 6
okcode.Font = Enum.Font.Gotham
okcode.Text = "Ok"
okcode.TextColor3 = Color3.fromRGB(0, 86, 255)
okcode.TextSize = 25.000
local isActivated = false
okcode.MouseButton1Up:Connect(function()
	for i,code in pairs(codes) do
		if CodeBox.Text == code then
			isActivated = true
		end

	end
	if isActivated == true then
		CodeFrame:Destroy()
		CodeFrame.Visible = false
		Gui.Visible = true
	end
end)

codeokround.Name = "codeokround"
codeokround.Parent = okcode
codeokround.Active = true
codeokround.AnchorPoint = Vector2.new(0.5, 0.5)
codeokround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
codeokround.BackgroundTransparency = 1.000
codeokround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
codeokround.Selectable = true
codeokround.Size = UDim2.new(1, 0, 1, 0)
codeokround.ZIndex = 3
codeokround.Image = "rbxassetid://3570695787"
codeokround.ImageColor3 = Color3.fromRGB(66, 66, 66)
codeokround.ScaleType = Enum.ScaleType.Slice
codeokround.SliceCenter = Rect.new(100, 100, 100, 100)
codeokround.SliceScale = 0.120

GameChecker.Name = "GameChecker"
GameChecker.Parent = Gui
GameChecker.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
GameChecker.BackgroundTransparency = 1.000
GameChecker.Position = UDim2.new(0.01, 0,0.933, 0)
GameChecker.Size = UDim2.new(0, 371,0, 26)
GameChecker.Font = Enum.Font.Gotham
GameChecker.Text = "Welcome! Arsenal is supported by deyol's modules!"
GameChecker.TextColor3 = Color3.fromRGB(255, 255, 255)
GameChecker.TextSize = 14.000
print(game.PlaceId)

if game.PlaceId == 286090429 or game.PlaceId == 606849621 or game.PlaceId == 155615604 then
	GameChecker.Text = "Welcome! This is supported by Mercury!" 
else
	GameChecker.Text = "Oops! This game isn't supported by Mercury!" 
end

Gui.Draggable = true
Gui.Selectable = true
Gui.Active = true
CodeFrame.Draggable = true
CodeFrame.Selectable = true
CodeFrame.Active = true

local counter5 = 0
mouse.KeyDown:connect(function(key)
	if key == "l" then
		counter5 = counter5 + 1
		if counter5 == 1 and CodeFrame.Visible == false and isActivated == true then
			Gui.Visible = true
		end
		if counter5 >= 2 and CodeFrame.Visible == false and isActivated == true then
			Gui.Visible = false
			counter5 = 0
		end
	end

end)

GameTeleport.Name = "GameTeleport"
GameTeleport.Parent = ScrollingFrame
GameTeleport.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
GameTeleport.BackgroundTransparency = 1.000
GameTeleport.BorderSizePixel = 0
GameTeleport.Position = UDim2.new(0.0500000007, 0, 0.187571436, 0)
GameTeleport.Size = UDim2.new(0, 105, 0, 32)
GameTeleport.ZIndex = 2
GameTeleport.Font = Enum.Font.Gotham
GameTeleport.Text = "Game Teleport"
GameTeleport.TextColor3 = Color3.fromRGB(255, 255, 255)
GameTeleport.TextSize = 15.000
GameTeleport.MouseButton1Up:Connect(function()
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	GameTPFrame.Visible = true
end)

ezz.Name = "ezz"
ezz.Parent = GameTeleport
ezz.Active = true
ezz.AnchorPoint = Vector2.new(0.5, 0.5)
ezz.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ezz.BackgroundTransparency = 1.000
ezz.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
ezz.Selectable = true
ezz.Size = UDim2.new(1, 0, 1, 0)
ezz.Image = "rbxassetid://3570695787"
ezz.ImageColor3 = Color3.fromRGB(66, 66, 66)
ezz.ScaleType = Enum.ScaleType.Slice
ezz.SliceCenter = Rect.new(100, 100, 100, 100)
ezz.SliceScale = 0.120

GameTPFrame.Name = "GameTPFrame"
GameTPFrame.Parent = Gui
GameTPFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
GameTPFrame.BackgroundTransparency = 1.000
GameTPFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
GameTPFrame.Size = UDim2.new(0, 490, 0, 304)
GameTPFrame.ZIndex = 3
GameTPFrame.Image = "rbxassetid://3570695787"
GameTPFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
GameTPFrame.ScaleType = Enum.ScaleType.Slice
GameTPFrame.SliceCenter = Rect.new(100, 100, 100, 100)
GameTPFrame.SliceScale = 0.120
GameTPFrame.Visible = false

Title.Name = "Title"
Title.Parent = GameTPFrame
Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title.BackgroundTransparency = 1.000
Title.BorderSizePixel = 0
Title.Size = UDim2.new(0, 490, 0, 39)
Title.ZIndex = 4
Title.Font = Enum.Font.Gotham
Title.Text = "Game Teleports"
Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Title.TextSize = 35.000

Title_Roundify_12px.Name = "Title_Roundify_12px"
Title_Roundify_12px.Parent = Title
Title_Roundify_12px.AnchorPoint = Vector2.new(0.5, 0.5)
Title_Roundify_12px.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title_Roundify_12px.BackgroundTransparency = 1.000
Title_Roundify_12px.Position = UDim2.new(0.5, 0, 0.5, 0)
Title_Roundify_12px.Size = UDim2.new(1, 0, 1, 0)
Title_Roundify_12px.ZIndex = 3
Title_Roundify_12px.Image = "rbxassetid://3570695787"
Title_Roundify_12px.ImageColor3 = Color3.fromRGB(66, 66, 66)
Title_Roundify_12px.ScaleType = Enum.ScaleType.Slice
Title_Roundify_12px.SliceCenter = Rect.new(100, 100, 100, 100)
Title_Roundify_12px.SliceScale = 0.120

socaughtonma.Name = "socaughtonma"
socaughtonma.Parent = Title
socaughtonma.AnchorPoint = Vector2.new(0.5, 0.5)
socaughtonma.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
socaughtonma.BackgroundTransparency = 1.000
socaughtonma.Position = UDim2.new(0.5, 0, 0.5, 0)
socaughtonma.Size = UDim2.new(1, 0, 1, 0)
socaughtonma.ZIndex = 3
socaughtonma.Image = "rbxassetid://3570695787"
socaughtonma.ImageColor3 = Color3.fromRGB(66, 66, 66)
socaughtonma.ScaleType = Enum.ScaleType.Slice
socaughtonma.SliceCenter = Rect.new(100, 100, 100, 100)
socaughtonma.SliceScale = 0.120

Jailbreak.Name = "Jailbreak"
Jailbreak.Parent = GameTPFrame
Jailbreak.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Jailbreak.BackgroundTransparency = 1.000
Jailbreak.BorderSizePixel = 0
Jailbreak.Position = UDim2.new(0.0489550531, 0, 0.187631607, 0)
Jailbreak.Size = UDim2.new(0, 162, 0, 47)
Jailbreak.ZIndex = 4
Jailbreak.Font = Enum.Font.Gotham
Jailbreak.Text = "Jailbreak"
Jailbreak.TextColor3 = Color3.fromRGB(255, 255, 255)
Jailbreak.TextSize = 25.000
Jailbreak.MouseButton1Up:Connect(function()
	TPservice:Teleport("606849621", game.Players.LocalPlayer)
end)

jail.Name = "jail"
jail.Parent = Jailbreak
jail.Active = true
jail.AnchorPoint = Vector2.new(0.5, 0.5)
jail.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
jail.BackgroundTransparency = 1.000
jail.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
jail.Selectable = true
jail.Size = UDim2.new(1, 0, 1, 0)
jail.ZIndex = 3
jail.Image = "rbxassetid://3570695787"
jail.ImageColor3 = Color3.fromRGB(66, 66, 66)
jail.ScaleType = Enum.ScaleType.Slice
jail.SliceCenter = Rect.new(100, 100, 100, 100)
jail.SliceScale = 0.120

Prisonlife.Name = "Prisonlife"
Prisonlife.Parent = GameTPFrame
Prisonlife.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Prisonlife.BackgroundTransparency = 1.000
Prisonlife.BorderSizePixel = 0
Prisonlife.Position = UDim2.new(0.563240767, 0, 0.184342131, 0)
Prisonlife.Size = UDim2.new(0, 162, 0, 47)
Prisonlife.ZIndex = 4
Prisonlife.Font = Enum.Font.Gotham
Prisonlife.Text = "PrisonLife"
Prisonlife.TextColor3 = Color3.fromRGB(255, 255, 255)
Prisonlife.TextSize = 25.000
Prisonlife.MouseButton1Up:Connect(function()
	TPservice:Teleport("155615604", game.Players.LocalPlayer)
end)

prison.Name = "prison"
prison.Parent = Prisonlife
prison.Active = true
prison.AnchorPoint = Vector2.new(0.5, 0.5)
prison.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
prison.BackgroundTransparency = 1.000
prison.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
prison.Selectable = true
prison.Size = UDim2.new(1, 0, 1, 0)
prison.ZIndex = 3
prison.Image = "rbxassetid://3570695787"
prison.ImageColor3 = Color3.fromRGB(66, 66, 66)
prison.ScaleType = Enum.ScaleType.Slice
prison.SliceCenter = Rect.new(100, 100, 100, 100)
prison.SliceScale = 0.120

AdoptMe.Name = "Arsenal"
AdoptMe.Parent = GameTPFrame
AdoptMe.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
AdoptMe.BackgroundTransparency = 1.000
AdoptMe.BorderSizePixel = 0
AdoptMe.Position = UDim2.new(0.0469142199, 0, 0.585657895, 0)
AdoptMe.Size = UDim2.new(0, 162, 0, 47)
AdoptMe.ZIndex = 4
AdoptMe.Font = Enum.Font.Gotham
AdoptMe.Text = "Arsenal"
AdoptMe.TextColor3 = Color3.fromRGB(255, 255, 255)
AdoptMe.TextSize = 25.000
AdoptMe.MouseButton1Up:Connect(function()
	TPservice:Teleport("286090429", game.Players.LocalPlayer)
end)

adopt.Name = "adopt"
adopt.Parent = AdoptMe
adopt.Active = true
adopt.AnchorPoint = Vector2.new(0.5, 0.5)
adopt.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
adopt.BackgroundTransparency = 1.000
adopt.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
adopt.Selectable = true
adopt.Size = UDim2.new(1, 0, 1, 0)
adopt.ZIndex = 3
adopt.Image = "rbxassetid://3570695787"
adopt.ImageColor3 = Color3.fromRGB(66, 66, 66)
adopt.ScaleType = Enum.ScaleType.Slice
adopt.SliceCenter = Rect.new(100, 100, 100, 100)
adopt.SliceScale = 0.120

Plsdonate.Name = "Plsdonate"
Plsdonate.Parent = GameTPFrame
Plsdonate.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Plsdonate.BackgroundTransparency = 1.000
Plsdonate.BorderSizePixel = 0
Plsdonate.Position = UDim2.new(0.561199963, 0, 0.588947356, 0)
Plsdonate.Size = UDim2.new(0, 162, 0, 47)
Plsdonate.ZIndex = 4
Plsdonate.Font = Enum.Font.Gotham
Plsdonate.Text = "Pls donate"
Plsdonate.TextColor3 = Color3.fromRGB(255, 255, 255)
Plsdonate.TextSize = 25.000
Plsdonate.MouseButton1Up:Connect(function()
	TPservice:Teleport("8737602449", game.Players.LocalPlayer)
end)

pls.Name = "pls"
pls.Parent = Plsdonate
pls.Active = true
pls.AnchorPoint = Vector2.new(0.5, 0.5)
pls.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
pls.BackgroundTransparency = 1.000
pls.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
pls.Selectable = true
pls.Size = UDim2.new(1, 0, 1, 0)
pls.ZIndex = 3
pls.Image = "rbxassetid://3570695787"
pls.ImageColor3 = Color3.fromRGB(66, 66, 66)
pls.ScaleType = Enum.ScaleType.Slice
pls.SliceCenter = Rect.new(100, 100, 100, 100)
pls.SliceScale = 0.120

disabled1.Name = "disabled1"
disabled1.Parent = SpeedFrame
disabled1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
disabled1.BackgroundTransparency = 1.000
disabled1.BorderSizePixel = 0
disabled1.Position = UDim2.new(0.170032486, 0, 0.457368463, 0)
disabled1.Size = UDim2.new(0, 106, 0, 33)
disabled1.ZIndex = 3
disabled1.Font = Enum.Font.Gotham
disabled1.Text = "Disabled"
disabled1.TextColor3 = Color3.fromRGB(255, 255, 255)
disabled1.TextSize = 25.000

omgitsgabry1.Name = "omgitsgabry1"
omgitsgabry1.Parent = disabled1
omgitsgabry1.Active = true
omgitsgabry1.AnchorPoint = Vector2.new(0.5, 0.5)
omgitsgabry1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
omgitsgabry1.BackgroundTransparency = 1.000
omgitsgabry1.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
omgitsgabry1.Selectable = true
omgitsgabry1.Size = UDim2.new(1, 0, 1, 0)
omgitsgabry1.ZIndex = 2
omgitsgabry1.Image = "rbxassetid://3570695787"
omgitsgabry1.ImageColor3 = Color3.fromRGB(255, 0, 0)
omgitsgabry1.ScaleType = Enum.ScaleType.Slice
omgitsgabry1.SliceCenter = Rect.new(100, 100, 100, 100)
omgitsgabry1.SliceScale = 0.120

disabled2.Name = "disabled1"
disabled2.Parent = HighJumpFrame
disabled2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
disabled2.BackgroundTransparency = 1.000
disabled2.BorderSizePixel = 0
disabled2.Position = UDim2.new(0.170032486, 0, 0.457368463, 0)
disabled2.Size = UDim2.new(0, 106, 0, 33)
disabled2.ZIndex = 4
disabled2.Font = Enum.Font.Gotham
disabled2.Text = "Disabled"
disabled2.TextColor3 = Color3.fromRGB(255, 255, 255)
disabled2.TextSize = 25.000

omgitsgabry2.Name = "omgitsgabry1"
omgitsgabry2.Parent = disabled2
omgitsgabry2.Active = true
omgitsgabry2.AnchorPoint = Vector2.new(0.5, 0.5)
omgitsgabry2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
omgitsgabry2.BackgroundTransparency = 1.000
omgitsgabry2.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
omgitsgabry2.Selectable = true
omgitsgabry2.Size = UDim2.new(1, 0, 1, 0)
omgitsgabry2.ZIndex = 3
omgitsgabry2.Image = "rbxassetid://3570695787"
omgitsgabry2.ImageColor3 = Color3.fromRGB(255, 0, 0)
omgitsgabry2.ScaleType = Enum.ScaleType.Slice
omgitsgabry2.SliceCenter = Rect.new(100, 100, 100, 100)
omgitsgabry2.SliceScale = 0.120

ScrollingFrame.Parent = Gui
ScrollingFrame.Active = true
ScrollingFrame.BackgroundColor3 = Color3.fromRGB(106, 106, 106)
ScrollingFrame.BorderSizePixel = 0
ScrollingFrame.Position = UDim2.new(0.0188405812, 0, 0.193877548, 0)
ScrollingFrame.Size = UDim2.new(0, 129, 0, 304)


Speed.Name = "Speed"
Speed.Parent = ScrollingFrame
Speed.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Speed.BackgroundTransparency = 1.000
Speed.BorderSizePixel = 0
Speed.Position = UDim2.new(0.0500000007, 0, 0.00999999978, 0)
Speed.Size = UDim2.new(0, 105, 0, 32)
Speed.ZIndex = 2
Speed.Font = Enum.Font.Gotham
Speed.Text = "Speed"
Speed.TextColor3 = Color3.fromRGB(255, 255, 255)
Speed.TextSize = 25.000

TextButton_Roundify_12px.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px.Parent = Speed
TextButton_Roundify_12px.Active = true
TextButton_Roundify_12px.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px.BackgroundTransparency = 1.000
TextButton_Roundify_12px.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px.Selectable = true
TextButton_Roundify_12px.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px.SliceScale = 0.120
local counter1 = 0
Speed.MouseButton1Up:Connect(function()
	if InfJumpFrame.Visible == true or HighJump.Visible == true then
		InfJumpFrame.Visible = false
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	SpeedFrame.Visible = true
end)

HighJump.Name = "HighJump"
HighJump.Parent = ScrollingFrame
HighJump.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
HighJump.BackgroundTransparency = 1.000
HighJump.BorderSizePixel = 0
HighJump.Position = UDim2.new(0.0500000976, 0, 0.0729999989, 0)
HighJump.Size = UDim2.new(0, 105, 0, 32)
HighJump.ZIndex = 2
HighJump.Font = Enum.Font.Gotham
HighJump.Text = "HighJump"
HighJump.TextColor3 = Color3.fromRGB(255, 255, 255)
HighJump.TextSize = 20.000

TextButton_Roundify_12px_2.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px_2.Parent = HighJump
TextButton_Roundify_12px_2.Active = true
TextButton_Roundify_12px_2.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px_2.BackgroundTransparency = 1.000
TextButton_Roundify_12px_2.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px_2.Selectable = true
TextButton_Roundify_12px_2.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px_2.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px_2.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px_2.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px_2.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px_2.SliceScale = 0.120
local counter2 = 0
HighJump.MouseButton1Up:Connect(function()
	if InfJumpFrame.Visible == true or SpeedFrame.Visible == true then
		InfJumpFrame.Visible = false
		SpeedFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	HighJumpFrame.Visible = true
end)

TextLabel.Parent = Gui
TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.BackgroundTransparency = 1.000
TextLabel.BorderSizePixel = 0
TextLabel.Size = UDim2.new(0, 690, 0, 66)
TextLabel.ZIndex = 2
TextLabel.Font = Enum.Font.Gotham
TextLabel.Text = "   Mercury v2"
TextLabel.TextXAlignment = Enum.TextXAlignment.Left
TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.TextSize = 35.000

TextLabel_Roundify_12px.Name = "TextLabel_Roundify_12px"
TextLabel_Roundify_12px.Parent = TextLabel
TextLabel_Roundify_12px.AnchorPoint = Vector2.new(0.5, 0.5)
TextLabel_Roundify_12px.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_Roundify_12px.BackgroundTransparency = 1.000
TextLabel_Roundify_12px.Position = UDim2.new(0.5, 0, 0.5, 0)
TextLabel_Roundify_12px.Size = UDim2.new(1, 0, 1, 0)
TextLabel_Roundify_12px.Image = "rbxassetid://3570695787"
TextLabel_Roundify_12px.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextLabel_Roundify_12px.ScaleType = Enum.ScaleType.Slice
TextLabel_Roundify_12px.SliceCenter = Rect.new(100, 100, 100, 100)
TextLabel_Roundify_12px.SliceScale = 0.120

SpeedFrame.Name = "SpeedFrame"
SpeedFrame.Parent = Gui
SpeedFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SpeedFrame.BackgroundTransparency = 1.000
SpeedFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
SpeedFrame.Size = UDim2.new(0, 490, 0, 304)
SpeedFrame.Visible = false
SpeedFrame.Image = "rbxassetid://3570695787"
SpeedFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
SpeedFrame.ScaleType = Enum.ScaleType.Slice
SpeedFrame.SliceCenter = Rect.new(100, 100, 100, 100)
SpeedFrame.SliceScale = 0.120

SpeedModification.Name = "SpeedModification"
SpeedModification.Parent = SpeedFrame
SpeedModification.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SpeedModification.BackgroundTransparency = 1.000
SpeedModification.BorderSizePixel = 0
SpeedModification.Size = UDim2.new(0, 490, 0, 39)
SpeedModification.ZIndex = 2
SpeedModification.Font = Enum.Font.Gotham
SpeedModification.Text = "Speed Modification"
SpeedModification.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedModification.TextSize = 35.000

TextLabel_Roundify_12px_2.Name = "TextLabel_Roundify_12px"
TextLabel_Roundify_12px_2.Parent = SpeedModification
TextLabel_Roundify_12px_2.AnchorPoint = Vector2.new(0.5, 0.5)
TextLabel_Roundify_12px_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_Roundify_12px_2.BackgroundTransparency = 1.000
TextLabel_Roundify_12px_2.Position = UDim2.new(0.5, 0, 0.5, 0)
TextLabel_Roundify_12px_2.Size = UDim2.new(1, 0, 1, 0)
TextLabel_Roundify_12px_2.Image = "rbxassetid://3570695787"
TextLabel_Roundify_12px_2.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextLabel_Roundify_12px_2.ScaleType = Enum.ScaleType.Slice
TextLabel_Roundify_12px_2.SliceCenter = Rect.new(100, 100, 100, 100)
TextLabel_Roundify_12px_2.SliceScale = 0.120

SpeedBox.Name = "SpeedBox"
SpeedBox.Parent = SpeedFrame
SpeedBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SpeedBox.BackgroundTransparency = 1.000
SpeedBox.BorderSizePixel = 0
SpeedBox.Position = UDim2.new(0.0285714287, 0, 0.319999993, 0)
SpeedBox.Size = UDim2.new(0, 172, 0, 39)
SpeedBox.ZIndex = 2
SpeedBox.Font = Enum.Font.Gotham
SpeedBox.Text = ""
SpeedBox.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedBox.TextSize = 14.000

TextBox_Roundify_12px.Name = "TextBox_Roundify_12px"
TextBox_Roundify_12px.Parent = SpeedBox
TextBox_Roundify_12px.Active = true
TextBox_Roundify_12px.AnchorPoint = Vector2.new(0.5, 0.5)
TextBox_Roundify_12px.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextBox_Roundify_12px.BackgroundTransparency = 1.000
TextBox_Roundify_12px.Position = UDim2.new(0.5057441, 0, 0.4830513, 0)
TextBox_Roundify_12px.Selectable = true
TextBox_Roundify_12px.Size = UDim2.new(1, 0, 1, 0)
TextBox_Roundify_12px.Image = "rbxassetid://3570695787"
TextBox_Roundify_12px.ImageColor3 = Color3.fromRGB(84, 84, 84)
TextBox_Roundify_12px.ScaleType = Enum.ScaleType.Slice
TextBox_Roundify_12px.SliceCenter = Rect.new(100, 100, 100, 100)
TextBox_Roundify_12px.SliceScale = 0.120

somethignspeed.Name = "somethignspeed"
somethignspeed.Parent = SpeedFrame
somethignspeed.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
somethignspeed.BackgroundTransparency = 1.000
somethignspeed.Position = UDim2.new(-0.0163510703, 0, 0.147499993, 0)
somethignspeed.Size = UDim2.new(0, 217, 0, 54)
somethignspeed.Font = Enum.Font.Gotham
somethignspeed.Text = "Choose the Speed(Normal 16)"
somethignspeed.TextColor3 = Color3.fromRGB(255, 255, 255)
somethignspeed.TextSize = 20.000
somethignspeed.TextWrapped = true

Ok.Name = "Ok"
Ok.Parent = SpeedFrame
Ok.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Ok.BackgroundTransparency = 1.000
Ok.BorderSizePixel = 0
Ok.Position = UDim2.new(0.0305877067, 0, 0.457368463, 0)
Ok.Size = UDim2.new(0, 48, 0, 34)
Ok.ZIndex = 2
Ok.Font = Enum.Font.Gotham
Ok.Text = "Ok"
Ok.TextColor3 = Color3.fromRGB(255, 255, 255)
Ok.TextSize = 25.000

TextButton_Roundify_12px_3.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px_3.Parent = Ok
TextButton_Roundify_12px_3.Active = true
TextButton_Roundify_12px_3.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px_3.BackgroundTransparency = 1.000
TextButton_Roundify_12px_3.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px_3.Selectable = true
TextButton_Roundify_12px_3.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px_3.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px_3.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px_3.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px_3.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px_3.SliceScale = 0.120
local counter71 = 0
Ok.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer
	counter71 = counter71 + 1
	if counter71 == 1 then
		disabled1.Text = "Enabled"
		omgitsgabry1.ImageColor3 = Color3.fromRGB(0,255,0)
		player.Character.Humanoid.WalkSpeed = tonumber(SpeedBox.Text)
	end
	if counter71 >= 2 then
		disabled1.Text = "Disabled"
		omgitsgabry1.ImageColor3 = Color3.fromRGB(255,0,0)
		player.Character.Humanoid.WalkSpeed = 16
		counter71 = 0
	end
end)

HighJumpFrame.Name = "HighJumpFrame"
HighJumpFrame.Parent = Gui
HighJumpFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
HighJumpFrame.BackgroundTransparency = 1.000
HighJumpFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
HighJumpFrame.Size = UDim2.new(0, 490, 0, 304)
HighJumpFrame.Visible = false
HighJumpFrame.Image = "rbxassetid://3570695787"
HighJumpFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
HighJumpFrame.ScaleType = Enum.ScaleType.Slice
HighJumpFrame.SliceCenter = Rect.new(100, 100, 100, 100)
HighJumpFrame.SliceScale = 0.120

HighJumpModification.Name = "HighJumpModification"
HighJumpModification.Parent = HighJumpFrame
HighJumpModification.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
HighJumpModification.BackgroundTransparency = 1.000
HighJumpModification.BorderSizePixel = 0
HighJumpModification.Size = UDim2.new(0, 490, 0, 39)
HighJumpModification.ZIndex = 2
HighJumpModification.Font = Enum.Font.Gotham
HighJumpModification.Text = "High Jump Modification"
HighJumpModification.TextColor3 = Color3.fromRGB(255, 255, 255)
HighJumpModification.TextSize = 35.000

TextLabel_Roundify_12px_3.Name = "TextLabel_Roundify_12px"
TextLabel_Roundify_12px_3.Parent = HighJumpModification
TextLabel_Roundify_12px_3.AnchorPoint = Vector2.new(0.5, 0.5)
TextLabel_Roundify_12px_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_Roundify_12px_3.BackgroundTransparency = 1.000
TextLabel_Roundify_12px_3.Position = UDim2.new(0.5, 0, 0.5, 0)
TextLabel_Roundify_12px_3.Size = UDim2.new(1, 0, 1, 0)
TextLabel_Roundify_12px_3.Image = "rbxassetid://3570695787"
TextLabel_Roundify_12px_3.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextLabel_Roundify_12px_3.ScaleType = Enum.ScaleType.Slice
TextLabel_Roundify_12px_3.SliceCenter = Rect.new(100, 100, 100, 100)
TextLabel_Roundify_12px_3.SliceScale = 0.120

JumpBox.Name = "JumpBox"
JumpBox.Parent = HighJumpFrame
JumpBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
JumpBox.BackgroundTransparency = 1.000
JumpBox.BorderSizePixel = 0
JumpBox.Position = UDim2.new(0.0285714287, 0, 0.319999993, 0)
JumpBox.Size = UDim2.new(0, 172, 0, 39)
JumpBox.ZIndex = 2
JumpBox.Font = Enum.Font.Gotham
JumpBox.Text = ""
JumpBox.TextColor3 = Color3.fromRGB(255, 255, 255)
JumpBox.TextSize = 14.000

TextBox_Roundify_12px_2.Name = "TextBox_Roundify_12px"
TextBox_Roundify_12px_2.Parent = JumpBox
TextBox_Roundify_12px_2.Active = true
TextBox_Roundify_12px_2.AnchorPoint = Vector2.new(0.5, 0.5)
TextBox_Roundify_12px_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextBox_Roundify_12px_2.BackgroundTransparency = 1.000
TextBox_Roundify_12px_2.Position = UDim2.new(0.5057441, 0, 0.4830513, 0)
TextBox_Roundify_12px_2.Selectable = true
TextBox_Roundify_12px_2.Size = UDim2.new(1, 0, 1, 0)
TextBox_Roundify_12px_2.Image = "rbxassetid://3570695787"
TextBox_Roundify_12px_2.ImageColor3 = Color3.fromRGB(84, 84, 84)
TextBox_Roundify_12px_2.ScaleType = Enum.ScaleType.Slice
TextBox_Roundify_12px_2.SliceCenter = Rect.new(100, 100, 100, 100)
TextBox_Roundify_12px_2.SliceScale = 0.120

somethignjump.Name = "somethignjump"
somethignjump.Parent = HighJumpFrame
somethignjump.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
somethignjump.BackgroundTransparency = 1.000
somethignjump.Position = UDim2.new(-0.0163510703, 0, 0.147499993, 0)
somethignjump.Size = UDim2.new(0, 217, 0, 54)
somethignjump.Font = Enum.Font.Gotham
somethignjump.Text = "Choose the Jump Power(Normal 50)"
somethignjump.TextColor3 = Color3.fromRGB(255, 255, 255)
somethignjump.TextSize = 20.000
somethignjump.TextWrapped = true

Ok_2.Name = "Ok"
Ok_2.Parent = HighJumpFrame
Ok_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Ok_2.BackgroundTransparency = 1.000
Ok_2.BorderSizePixel = 0
Ok_2.Position = UDim2.new(0.0305877067, 0, 0.457368463, 0)
Ok_2.Size = UDim2.new(0, 48, 0, 34)
Ok_2.ZIndex = 2
Ok_2.Font = Enum.Font.Gotham
Ok_2.Text = "Ok"
Ok_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Ok_2.TextSize = 25.000
local counter34 = 0
Ok_2.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer
	counter34 = counter34 + 1
	if counter34 == 1 then
		player.Character.Humanoid.JumpPower = tonumber(JumpBox.Text)
		disabled2.Text = "Enabled"
		omgitsgabry2.ImageColor3 = Color3.fromRGB(0,255,0)
	end
	if counter34 >= 2 then
		player.Character.Humanoid.JumpPower = 50
		disabled2.Text = "Disabled"
		omgitsgabry2.ImageColor3 = Color3.fromRGB(255,0,0)
		counter34 = 0
	end

end)

TextButton_Roundify_12px_4.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px_4.Parent = Ok_2
TextButton_Roundify_12px_4.Active = true
TextButton_Roundify_12px_4.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px_4.BackgroundTransparency = 1.000
TextButton_Roundify_12px_4.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px_4.Selectable = true
TextButton_Roundify_12px_4.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px_4.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px_4.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px_4.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px_4.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px_4.SliceScale = 0.120


InfJumpFrame.Name = "InfJumpFrame"
InfJumpFrame.Parent = Gui
InfJumpFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InfJumpFrame.BackgroundTransparency = 1.000
InfJumpFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
InfJumpFrame.Size = UDim2.new(0, 490, 0, 304)
InfJumpFrame.ZIndex = 3
InfJumpFrame.Image = "rbxassetid://3570695787"
InfJumpFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
InfJumpFrame.ScaleType = Enum.ScaleType.Slice
InfJumpFrame.SliceCenter = Rect.new(100, 100, 100, 100)
InfJumpFrame.SliceScale = 0.120
InfJumpFrame.Visible = false

InfJumpModification.Name = "InfJumpModification"
InfJumpModification.Parent = InfJumpFrame
InfJumpModification.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InfJumpModification.BackgroundTransparency = 1.000
InfJumpModification.BorderSizePixel = 0
InfJumpModification.Size = UDim2.new(0, 490, 0, 39)
InfJumpModification.ZIndex = 4
InfJumpModification.Font = Enum.Font.Gotham
InfJumpModification.Text = "InfJump Modification"
InfJumpModification.TextColor3 = Color3.fromRGB(255, 255, 255)
InfJumpModification.TextSize = 35.000

socaughtonma.Name = "socaughtonma"
socaughtonma.Parent = InfJumpModification
socaughtonma.AnchorPoint = Vector2.new(0.5, 0.5)
socaughtonma.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
socaughtonma.BackgroundTransparency = 1.000
socaughtonma.Position = UDim2.new(0.5, 0, 0.5, 0)
socaughtonma.Size = UDim2.new(1, 0, 1, 0)
socaughtonma.ZIndex = 3
socaughtonma.Image = "rbxassetid://3570695787"
socaughtonma.ImageColor3 = Color3.fromRGB(66, 66, 66)
socaughtonma.ScaleType = Enum.ScaleType.Slice
socaughtonma.SliceCenter = Rect.new(100, 100, 100, 100)
socaughtonma.SliceScale = 0.120

InfBox.Name = "InfBox"
InfBox.Parent = InfJumpFrame
InfBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InfBox.BackgroundTransparency = 1.000
InfBox.BorderSizePixel = 0
InfBox.Position = UDim2.new(0.0285714287, 0, 0.319999993, 0)
InfBox.Size = UDim2.new(0, 55, 0, 39)
InfBox.ZIndex = 4
InfBox.Font = Enum.Font.Gotham
InfBox.Text = ""
InfBox.TextColor3 = Color3.fromRGB(255, 255, 255)
InfBox.TextSize = 14.000

ify.Name = "ify"
ify.Parent = InfBox
ify.Active = true
ify.AnchorPoint = Vector2.new(0.5, 0.5)
ify.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ify.BackgroundTransparency = 1.000
ify.Position = UDim2.new(0.5057441, 0, 0.4830513, 0)
ify.Selectable = true
ify.Size = UDim2.new(1, 0, 1, 0)
ify.ZIndex = 3
ify.Image = "rbxassetid://3570695787"
ify.ImageColor3 = Color3.fromRGB(84, 84, 84)
ify.ScaleType = Enum.ScaleType.Slice
ify.SliceCenter = Rect.new(100, 100, 100, 100)
ify.SliceScale = 0.120

somethigninf.Name = "somethigninf"
somethigninf.Parent = InfJumpFrame
somethigninf.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
somethigninf.BackgroundTransparency = 1.000
somethigninf.Position = UDim2.new(-2.45403498e-05, 0, 0.137631565, 0)
somethigninf.Size = UDim2.new(0, 217, 0, 54)
somethigninf.ZIndex = 4
somethigninf.Font = Enum.Font.Gotham
somethigninf.Text = "Choose the keypress you want the InfJump to be on"
somethigninf.TextColor3 = Color3.fromRGB(255, 255, 255)
somethigninf.TextSize = 17.000
somethigninf.TextWrapped = true

OkInfJump.Name = "OkInfJump"
OkInfJump.Parent = InfJumpFrame
OkInfJump.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
OkInfJump.BackgroundTransparency = 1.000
OkInfJump.BorderSizePixel = 0
OkInfJump.Position = UDim2.new(0.0305877067, 0, 0.457368463, 0)
OkInfJump.Size = UDim2.new(0, 48, 0, 34)
OkInfJump.ZIndex = 6
OkInfJump.Font = Enum.Font.Gotham
OkInfJump.Text = "Ok"
OkInfJump.TextColor3 = Color3.fromRGB(255, 255, 255)
OkInfJump.TextSize = 25.000
local counter52 = 0
disabled.Name = "disabled"
disabled.Parent = InfJumpFrame
disabled.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
disabled.BackgroundTransparency = 1.000
disabled.BorderSizePixel = 0
disabled.Position = UDim2.new(0.170032486, 0, 0.457368463, 0)
disabled.Size = UDim2.new(0, 106, 0, 33)
disabled.ZIndex = 5
disabled.Font = Enum.Font.Gotham
disabled.Text = "Disabled"
disabled.TextColor3 = Color3.fromRGB(255, 255, 255)
disabled.TextSize = 25.000

omgitsgabry.Name = "omgitsgabry"
omgitsgabry.Parent = disabled
omgitsgabry.Active = true
omgitsgabry.AnchorPoint = Vector2.new(0.5, 0.5)
omgitsgabry.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
omgitsgabry.BackgroundTransparency = 1.000
omgitsgabry.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
omgitsgabry.Selectable = true
omgitsgabry.Size = UDim2.new(1, 0, 1, 0)
omgitsgabry.ZIndex = 3
omgitsgabry.Image = "rbxassetid://3570695787"
omgitsgabry.ImageColor3 = Color3.fromRGB(255, 0, 0)
omgitsgabry.ScaleType = Enum.ScaleType.Slice
omgitsgabry.SliceCenter = Rect.new(100, 100, 100, 100)
omgitsgabry.SliceScale = 0.120
OkInfJump.MouseButton1Up:Connect(function()
	counter52 = counter52 + 1
	omgitsgabry.ImageColor3 = Color3.fromRGB(0,255,0)
	disabled.Text = "Enabled"
	local player = game.Players.LocalPlayer
	local mouse = player:GetMouse()  
	mouse.KeyDown:connect(function(key)
		if key == InfBox.Text and counter52 == 1 then
			player.Character.Humanoid:ChangeState(Enum.HumanoidStateType.Jumping)
		end
	end)
	if counter52 >=2 then
		counter52 = 0
		disabled.Text = "Disabled"
		omgitsgabry.ImageColor3 = Color3.fromRGB(255, 0, 0)
	end
end)

round.Name = "round"
round.Parent = OkInfJump
round.Active = true
round.AnchorPoint = Vector2.new(0.5, 0.5)
round.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
round.BackgroundTransparency = 1.000
round.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
round.Selectable = true
round.Size = UDim2.new(1, 0, 1, 0)
round.ZIndex = 3
round.Image = "rbxassetid://3570695787"
round.ImageColor3 = Color3.fromRGB(66, 66, 66)
round.ScaleType = Enum.ScaleType.Slice
round.SliceCenter = Rect.new(100, 100, 100, 100)
round.SliceScale = 0.120

InfJump.Name = "InfJump"
InfJump.Parent = ScrollingFrame
InfJump.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InfJump.BackgroundTransparency = 1.000
InfJump.BorderSizePixel = 0
InfJump.Position = UDim2.new(0.0500000007, 0, 0.134000003, 0)
InfJump.Size = UDim2.new(0, 105, 0, 32)
InfJump.ZIndex = 2
InfJump.Font = Enum.Font.Gotham
InfJump.Text = "InfJump"
InfJump.TextColor3 = Color3.fromRGB(255, 255, 255)
InfJump.TextSize = 20.000
local countergabry = 0
InfJump.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	InfJumpFrame.Visible = true

end)

TextButton_Roundify_12px_9.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px_9.Parent = InfJump
TextButton_Roundify_12px_9.Active = true
TextButton_Roundify_12px_9.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px_9.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px_9.BackgroundTransparency = 1.000
TextButton_Roundify_12px_9.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px_9.Selectable = true
TextButton_Roundify_12px_9.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px_9.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px_9.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px_9.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px_9.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px_9.SliceScale = 0.120

madeby.Name = "madeby"
madeby.Parent = Gui
madeby.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
madeby.BackgroundTransparency = 1.000
madeby.Position = UDim2.new(0.769565225, 0, -0.00255090371, 0)
madeby.Size = UDim2.new(0, 159, 0, 26)
madeby.Font = Enum.Font.Gotham
madeby.Text = "Made by deyol#6075"
madeby.TextColor3 = Color3.fromRGB(255, 255, 255)
madeby.TextSize = 14.000
madeby.ZIndex = 4


Invisibility.Name = "Invisibility"
Invisibility.Parent = ScrollingFrame
Invisibility.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Invisibility.BackgroundTransparency = 1.000
Invisibility.BorderSizePixel = 0
Invisibility.Position = UDim2.new(0.0500000007, 0, 0.242142856, 0)
Invisibility.Size = UDim2.new(0, 105, 0, 32)
Invisibility.ZIndex = 2
Invisibility.Font = Enum.Font.Gotham
Invisibility.Text = "Invisibility"
Invisibility.TextColor3 = Color3.fromRGB(112, 0, 255)
Invisibility.TextSize = 18.000
Invisibility.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	InvisibilityFrame.Visible = true
end)

TextButton_Roundify_12px_0.Name = "TextButton_Roundify_12px"
TextButton_Roundify_12px_0.Parent = Invisibility
TextButton_Roundify_12px_0.Active = true
TextButton_Roundify_12px_0.AnchorPoint = Vector2.new(0.5, 0.5)
TextButton_Roundify_12px_0.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton_Roundify_12px_0.BackgroundTransparency = 1.000
TextButton_Roundify_12px_0.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
TextButton_Roundify_12px_0.Selectable = true
TextButton_Roundify_12px_0.Size = UDim2.new(1, 0, 1, 0)
TextButton_Roundify_12px_0.Image = "rbxassetid://3570695787"
TextButton_Roundify_12px_0.ImageColor3 = Color3.fromRGB(66, 66, 66)
TextButton_Roundify_12px_0.ScaleType = Enum.ScaleType.Slice
TextButton_Roundify_12px_0.SliceCenter = Rect.new(100, 100, 100, 100)
TextButton_Roundify_12px_0.SliceScale = 0.120

InvisibilityFrame.Name = "InvisibilityFrame"
InvisibilityFrame.Parent = Gui
InvisibilityFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InvisibilityFrame.BackgroundTransparency = 1.000
InvisibilityFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
InvisibilityFrame.Size = UDim2.new(0, 490, 0, 304)
InvisibilityFrame.Image = "rbxassetid://3570695787"
InvisibilityFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
InvisibilityFrame.ScaleType = Enum.ScaleType.Slice
InvisibilityFrame.SliceCenter = Rect.new(100, 100, 100, 100)
InvisibilityFrame.SliceScale = 0.120
InvisibilityFrame.Visible = false

disabled7.Name = "disabled7"
disabled7.Parent = InvisibilityFrame
disabled7.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
disabled7.BackgroundTransparency = 1.000
disabled7.BorderSizePixel = 0
disabled7.Position = UDim2.new(0.182277381, 0, 0.184342146, 0)
disabled7.Size = UDim2.new(0, 106, 0, 33)
disabled7.ZIndex = 4
disabled7.Font = Enum.Font.Gotham
disabled7.Text = "Disabled"
disabled7.TextColor3 = Color3.fromRGB(255, 255, 255)
disabled7.TextSize = 25.000

omgitsgabry7.Name = "omgitsgabry7"
omgitsgabry7.Parent = disabled7
omgitsgabry7.Active = true
omgitsgabry7.AnchorPoint = Vector2.new(0.5, 0.5)
omgitsgabry7.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
omgitsgabry7.BackgroundTransparency = 1.000
omgitsgabry7.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
omgitsgabry7.Selectable = true
omgitsgabry7.Size = UDim2.new(1, 0, 1, 0)
omgitsgabry7.ZIndex = 3
omgitsgabry7.Image = "rbxassetid://3570695787"
omgitsgabry7.ImageColor3 = Color3.fromRGB(255, 0, 0)
omgitsgabry7.ScaleType = Enum.ScaleType.Slice
omgitsgabry7.SliceCenter = Rect.new(100, 100, 100, 100)
omgitsgabry7.SliceScale = 0.120

InvisibilityMod.Name = "InvisibilityMod"
InvisibilityMod.Parent = InvisibilityFrame
InvisibilityMod.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InvisibilityMod.BackgroundTransparency = 1.000
InvisibilityMod.BorderSizePixel = 0
InvisibilityMod.Size = UDim2.new(0, 490, 0, 39)
InvisibilityMod.ZIndex = 2
InvisibilityMod.Font = Enum.Font.Gotham
InvisibilityMod.Text = "Invisibility"
InvisibilityMod.TextColor3 = Color3.fromRGB(112, 0, 255)
InvisibilityMod.TextSize = 35.000

modround.Name = "modround"
modround.Parent = InvisibilityMod
modround.AnchorPoint = Vector2.new(0.5, 0.5)
modround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
modround.BackgroundTransparency = 1.000
modround.Position = UDim2.new(0.5, 0, 0.5, 0)
modround.Size = UDim2.new(1, 0, 1, 0)
modround.Image = "rbxassetid://3570695787"
modround.ImageColor3 = Color3.fromRGB(66, 66, 66)
modround.ScaleType = Enum.ScaleType.Slice
modround.SliceCenter = Rect.new(100, 100, 100, 100)
modround.SliceScale = 0.120

invisok.Name = "invisok"
invisok.Parent = InvisibilityFrame
invisok.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
invisok.BackgroundTransparency = 1.000
invisok.BorderSizePixel = 0
invisok.Position = UDim2.new(0.0428326055, 0, 0.184342146, 0)
invisok.Size = UDim2.new(0, 48, 0, 34)
invisok.ZIndex = 2
invisok.Font = Enum.Font.Gotham
invisok.Text = "Ok"
invisok.TextColor3 = Color3.fromRGB(112, 0, 255)
invisok.TextSize = 25.000
local counter32 = 0
invisok.MouseButton1Up:Connect(function()
	counter32 = counter32 + 1
	if counter32 == 1 then
		disabled7.Text = "Enabled"
		omgitsgabry7.ImageColor3 = Color3.fromRGB(0,255,0)
		for _, Part in pairs(player.Character:GetDescendants()) do
			if Part:IsA("BasePart") or Part:IsA("MeshPart") then
				Part.Transparency = 1
				player.Character.Head.face.Transparency = 1
				player.Character.HumanoidRootPart.Transparency = 1
			end
		end
	end

	if counter32 >= 2 then
		disabled7.Text = "Disabled"
		omgitsgabry7.ImageColor3 = Color3.fromRGB(255, 0, 0)
		for _, Part in pairs(player.Character:GetDescendants()) do
			if Part:IsA("BasePart") or Part:IsA("MeshPart") then
				Part.Transparency = 0
				player.Character.Head.face.Transparency = 0
				player.Character.HumanoidRootPart.Transparency = 1
			end
		end

		counter32 = 0
	end

end)

invisround.Name = "invisround"
invisround.Parent = invisok
invisround.Active = true
invisround.AnchorPoint = Vector2.new(0.5, 0.5)
invisround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
invisround.BackgroundTransparency = 1.000
invisround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
invisround.Selectable = true
invisround.Size = UDim2.new(1, 0, 1, 0)
invisround.Image = "rbxassetid://3570695787"
invisround.ImageColor3 = Color3.fromRGB(66, 66, 66)
invisround.ScaleType = Enum.ScaleType.Slice
invisround.SliceCenter = Rect.new(100, 100, 100, 100)
invisround.SliceScale = 0.120


Esp.Name = "Esp"
Esp.Parent = ScrollingFrame
Esp.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Esp.BackgroundTransparency = 1.000
Esp.BorderSizePixel = 0
Esp.Position = UDim2.new(0.0422480628, 0, 0.295714289, 0)
Esp.Size = UDim2.new(0, 105, 0, 32)
Esp.ZIndex = 2
Esp.Font = Enum.Font.Gotham
Esp.Text = "Esp"
Esp.TextColor3 = Color3.fromRGB(255, 0, 61)
Esp.TextSize = 18.000
Esp.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	EspFrame.Visible = true
end)

espround.Name = "espround"
espround.Parent = Esp
espround.Active = true
espround.AnchorPoint = Vector2.new(0.5, 0.5)
espround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
espround.BackgroundTransparency = 1.000
espround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
espround.Selectable = true
espround.Size = UDim2.new(1, 0, 1, 0)
espround.Image = "rbxassetid://3570695787"
espround.ImageColor3 = Color3.fromRGB(66, 66, 66)
espround.ScaleType = Enum.ScaleType.Slice
espround.SliceCenter = Rect.new(100, 100, 100, 100)
espround.SliceScale = 0.120

EspFrame.Name = "EspFrame"
EspFrame.Parent = Gui
EspFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
EspFrame.BackgroundTransparency = 1.000
EspFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
EspFrame.Size = UDim2.new(0, 490, 0, 304)
EspFrame.Image = "rbxassetid://3570695787"
EspFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
EspFrame.ScaleType = Enum.ScaleType.Slice
EspFrame.SliceCenter = Rect.new(100, 100, 100, 100)
EspFrame.SliceScale = 0.120
EspFrame.Visible = false

disabled71.Name = "disabled7"
disabled71.Parent = EspFrame
disabled71.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
disabled71.BackgroundTransparency = 1.000
disabled71.BorderSizePixel = 0
disabled71.Position = UDim2.new(0.182277381, 0, 0.184342146, 0)
disabled71.Size = UDim2.new(0, 106, 0, 33)
disabled71.ZIndex = 5
disabled71.Font = Enum.Font.Gotham
disabled71.Text = "Disabled"
disabled71.TextColor3 = Color3.fromRGB(255, 255, 255)
disabled71.TextSize = 25.000

omgitsgabry21.Name = "omgitsgabry21"
omgitsgabry21.Parent = disabled71
omgitsgabry21.Active = true
omgitsgabry21.AnchorPoint = Vector2.new(0.5, 0.5)
omgitsgabry21.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
omgitsgabry21.BackgroundTransparency = 1.000
omgitsgabry21.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
omgitsgabry21.Selectable = true
omgitsgabry21.Size = UDim2.new(1, 0, 1, 0)
omgitsgabry21.ZIndex = 4
omgitsgabry21.Image = "rbxassetid://3570695787"
omgitsgabry21.ImageColor3 = Color3.fromRGB(255, 0, 0)
omgitsgabry21.ScaleType = Enum.ScaleType.Slice
omgitsgabry21.SliceCenter = Rect.new(100, 100, 100, 100)
omgitsgabry21.SliceScale = 0.120

espmod.Name = "espmod"
espmod.Parent = EspFrame
espmod.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
espmod.BackgroundTransparency = 1.000
espmod.BorderSizePixel = 0
espmod.Size = UDim2.new(0, 490, 0, 39)
espmod.ZIndex = 2
espmod.Font = Enum.Font.Gotham
espmod.Text = "ESP"
espmod.TextColor3 = Color3.fromRGB(255, 0, 61)
espmod.TextSize = 35.000

espmodround.Name = "espmodround"
espmodround.Parent = espmod
espmodround.AnchorPoint = Vector2.new(0.5, 0.5)
espmodround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
espmodround.BackgroundTransparency = 1.000
espmodround.Position = UDim2.new(0.5, 0, 0.5, 0)
espmodround.Size = UDim2.new(1, 0, 1, 0)
espmodround.Image = "rbxassetid://3570695787"
espmodround.ImageColor3 = Color3.fromRGB(66, 66, 66)
espmodround.ScaleType = Enum.ScaleType.Slice
espmodround.SliceCenter = Rect.new(100, 100, 100, 100)
espmodround.SliceScale = 0.120

espok.Name = "espok"
espok.Parent = EspFrame
espok.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
espok.BackgroundTransparency = 1.000
espok.BorderSizePixel = 0
espok.Position = UDim2.new(0.0428326055, 0, 0.184342146, 0)
espok.Size = UDim2.new(0, 48, 0, 34)
espok.ZIndex = 2
espok.Font = Enum.Font.Gotham
espok.Text = "Ok"
espok.TextColor3 = Color3.fromRGB(255, 0, 61)
espok.TextSize = 25.000

teamcheck.Name = "teamcheck"
teamcheck.Parent = EspFrame
teamcheck.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
teamcheck.BackgroundTransparency = 1.000
teamcheck.BorderSizePixel = 0
teamcheck.Position = UDim2.new(0.0428326055, 0, 0.332368463, 0)
teamcheck.Size = UDim2.new(0, 147, 0, 34)
teamcheck.ZIndex = 2
teamcheck.Font = Enum.Font.Gotham
teamcheck.Text = "Team Check"
teamcheck.TextColor3 = Color3.fromRGB(255, 0, 183)
teamcheck.TextSize = 25.000
_G.TeamCheck = true

teamcheckdis.Name = "teamcheckdis"
teamcheckdis.Parent = teamcheck
teamcheckdis.Active = true
teamcheckdis.AnchorPoint = Vector2.new(0.5, 0.5)
teamcheckdis.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
teamcheckdis.BackgroundTransparency = 1.000
teamcheckdis.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
teamcheckdis.Selectable = true
teamcheckdis.Size = UDim2.new(1, 0, 1, 0)
teamcheckdis.Image = "rbxassetid://3570695787"
teamcheckdis.ImageColor3 = Color3.fromRGB(66, 66, 66)
teamcheckdis.ScaleType = Enum.ScaleType.Slice
teamcheckdis.SliceCenter = Rect.new(100, 100, 100, 100)
teamcheckdis.SliceScale = 0.120

teamcheckdis_2.Name = "teamcheckdis"
teamcheckdis_2.Parent = EspFrame
teamcheckdis_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
teamcheckdis_2.BackgroundTransparency = 1.000
teamcheckdis_2.BorderSizePixel = 0
teamcheckdis_2.Position = UDim2.new(0.365950853, 0, 0.332368463, 0)
teamcheckdis_2.Size = UDim2.new(0, 106, 0, 33)
teamcheckdis_2.ZIndex = 5
teamcheckdis_2.Font = Enum.Font.Gotham
teamcheckdis_2.Text = "Enabled"
teamcheckdis_2.TextColor3 = Color3.fromRGB(255, 255, 255)
teamcheckdis_2.TextSize = 25.000
teamcheck.MouseButton1Up:Connect(function()
	_G.TeamCheck = not _G.TeamCheck
	if _G.TeamCheck then
		teamcheckdisround.ImageColor3 = Color3.fromRGB(0,255,0)
		teamcheckdis_2.Text = "Enabled"
	end
	if not _G.TeamCheck then
		teamcheckdisround.ImageColor3 = Color3.fromRGB(255,0,0)
		teamcheckdis_2.Text = "Disabled"
	end
end)


teamcheckdisround.Name = "teamcheckdisround"
teamcheckdisround.Parent = teamcheckdis_2
teamcheckdisround.Active = true
teamcheckdisround.AnchorPoint = Vector2.new(0.5, 0.5)
teamcheckdisround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
teamcheckdisround.BackgroundTransparency = 1.000
teamcheckdisround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
teamcheckdisround.Selectable = true
teamcheckdisround.Size = UDim2.new(1, 0, 1, 0)
teamcheckdisround.ZIndex = 4
teamcheckdisround.Image = "rbxassetid://3570695787"
teamcheckdisround.ImageColor3 = Color3.fromRGB(110, 255, 0)
teamcheckdisround.ScaleType = Enum.ScaleType.Slice
teamcheckdisround.SliceCenter = Rect.new(100, 100, 100, 100)
teamcheckdisround.SliceScale = 0.120

local gui1 = Instance.new("BillboardGui")
local name = Instance.new("TextLabel")



gui1.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
gui1.Active = true
gui1.LightInfluence = 1.000
gui1.Size = UDim2.new(0, 200, 0, 50)
gui1.StudsOffset = Vector3.new(0, 2, 0)
gui1.AlwaysOnTop = true
gui1.ResetOnSpawn = false
gui1.LightInfluence = 0;
gui1.Size = UDim2.new(0, 200, 0, 50)
gui1.StudsOffset = Vector3.new(0, 2, 0)
name.Name = "name"
name.Parent = gui1
name.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
name.BackgroundTransparency = 1.000
name.Size = UDim2.new(0, 200, 0, 50)
name.BorderSizePixel = 0
name.Font = Enum.Font.Gotham
name.Text = ""
name.TextSize = 8
local counter65 = 0
espok.MouseButton1Up:Connect(function()
	counter65 = counter65 + 1
	if counter65 == 1 then
		omgitsgabry21.ImageColor3 = Color3.fromRGB(0,255,0)
		disabled71.Text = "Enabled"



		for i,v in pairs (game:GetService("Players"):GetPlayers()) do
			if v ~= game:GetService("Players").LocalPlayer and v.Character.Head:FindFirstChild("gui")==nil then
				if _G.TeamCheck then
					if v.Team ~= game:GetService("Players").LocalPlayer.Team then
						name.Visible = true
						name.TextColor3 = v.TeamColor.Color
						name.Text = v.Name
						gui1:Clone().Parent = v.Character.Head
					end
				else
					name.Visible = true
					name.TextColor3 = v.TeamColor.Color
					name.Text = v.Name
					gui1:Clone().Parent = v.Character.Head
				end

			end

		end



		while wait(10) do
			print("Checking!")
			for i,v in pairs(game:GetService("Players"):GetPlayers()) do
				if v ~= game:GetService("Players").LocalPlayer and v.Character.Head:FindFirstChild("gui")==nil and v.Team ~= game:GetService("Players").LocalPlayer.Team   then 
					print("Found someone!")
					if _G.TeamCheck then
						if v.Team ~= game:GetService("Players").LocalPlayer.Team then
							name.Visible = true
							name.TextColor3 = v.TeamColor.Color
							name.Text = v.Name
							gui1:Clone().Parent = v.Character.Head
						end
					else
						name.Visible = true
						name.TextColor3 = v.TeamColor.Color
						name.Text = v.Name
						gui1:Clone().Parent = v.Character.Head
					end
				end

			end
		end

	end

	if counter65 >= 2 then
		for i,v in pairs (game:GetService("Players"):GetPlayers()) do
			if v.Character:FindFirstChild("gui1") ~= nil then
				v.Character:FindFirstChild("gui1").name.Visible = false
			end
		end

		omgitsgabry21.ImageColor3 = Color3.fromRGB(255,0,0)
		disabled71.Text = "Disabled"
		counter65 = 0
	end


end)

espokround.Name = "espokround"
espokround.Parent = espok
espokround.Active = true
espokround.AnchorPoint = Vector2.new(0.5, 0.5)
espokround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
espokround.BackgroundTransparency = 1.000
espokround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
espokround.Selectable = true
espokround.Size = UDim2.new(1, 0, 1, 0)
espokround.Image = "rbxassetid://3570695787"
espokround.ImageColor3 = Color3.fromRGB(66, 66, 66)
espokround.ScaleType = Enum.ScaleType.Slice
espokround.SliceCenter = Rect.new(100, 100, 100, 100)
espokround.SliceScale = 0.120

ScriptsFrame.Name = "ScriptsFrame"
ScriptsFrame.Parent = Gui
ScriptsFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ScriptsFrame.BackgroundTransparency = 1.000
ScriptsFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
ScriptsFrame.Size = UDim2.new(0, 490, 0, 304)
ScriptsFrame.ZIndex = 3
ScriptsFrame.Image = "rbxassetid://3570695787"
ScriptsFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
ScriptsFrame.ScaleType = Enum.ScaleType.Slice
ScriptsFrame.SliceCenter = Rect.new(100, 100, 100, 100)
ScriptsFrame.SliceScale = 0.120
ScriptsFrame.Visible = false

othscriptitle.Name = "othscriptitle"
othscriptitle.Parent = ScriptsFrame
othscriptitle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
othscriptitle.BackgroundTransparency = 1.000
othscriptitle.BorderSizePixel = 0
othscriptitle.Size = UDim2.new(0, 490, 0, 39)
othscriptitle.ZIndex = 4
othscriptitle.Font = Enum.Font.Gotham
othscriptitle.Text = "Other Scripts"
othscriptitle.TextColor3 = Color3.fromRGB(173, 0, 255)
othscriptitle.TextSize = 35.000

othscrround.Name = "othscrround"
othscrround.Parent = othscriptitle
othscrround.AnchorPoint = Vector2.new(0.5, 0.5)
othscrround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
othscrround.BackgroundTransparency = 1.000
othscrround.Position = UDim2.new(0.5, 0, 0.5, 0)
othscrround.Size = UDim2.new(1, 0, 1, 0)
othscrround.ZIndex = 3
othscrround.Image = "rbxassetid://3570695787"
othscrround.ImageColor3 = Color3.fromRGB(66, 66, 66)
othscrround.ScaleType = Enum.ScaleType.Slice
othscrround.SliceCenter = Rect.new(100, 100, 100, 100)
othscrround.SliceScale = 0.120

OwlHub.Name = "OwlHub"
OwlHub.Parent = ScriptsFrame
OwlHub.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
OwlHub.BackgroundTransparency = 1.000
OwlHub.BorderSizePixel = 0
OwlHub.Position = UDim2.new(0.0489550531, 0, 0.187631607, 0)
OwlHub.Size = UDim2.new(0, 162, 0, 47)
OwlHub.ZIndex = 4
OwlHub.Font = Enum.Font.Gotham
OwlHub.Text = "Owl Hub"
OwlHub.TextColor3 = Color3.fromRGB(173, 0, 255)
OwlHub.TextSize = 25.000
OwlHub.MouseButton1Up:Connect(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt"))();
end)

owl.Name = "owl"
owl.Parent = OwlHub
owl.Active = true
owl.AnchorPoint = Vector2.new(0.5, 0.5)
owl.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
owl.BackgroundTransparency = 1.000
owl.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
owl.Selectable = true
owl.Size = UDim2.new(1, 0, 1, 0)
owl.ZIndex = 3
owl.Image = "rbxassetid://3570695787"
owl.ImageColor3 = Color3.fromRGB(66, 66, 66)
owl.ScaleType = Enum.ScaleType.Slice
owl.SliceCenter = Rect.new(100, 100, 100, 100)
owl.SliceScale = 0.120

Ivadmin.Name = "Ivadmin"
Ivadmin.Parent = ScriptsFrame
Ivadmin.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Ivadmin.BackgroundTransparency = 1.000
Ivadmin.BorderSizePixel = 0
Ivadmin.Position = UDim2.new(0.563240767, 0, 0.184342131, 0)
Ivadmin.Size = UDim2.new(0, 162, 0, 47)
Ivadmin.ZIndex = 4
Ivadmin.Font = Enum.Font.Gotham
Ivadmin.Text = "IV Admin"
Ivadmin.TextColor3 = Color3.fromRGB(173, 0, 255)
Ivadmin.TextSize = 25.000
Ivadmin.MouseButton1Up:Connect(function()
	loadstring(game:HttpGet('\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\79\109\110\105\112\111\116\101\110\99\101\68\101\118\101\108\111\112\101\114\47\78\117\109\98\101\114\47\109\97\105\110\47\49\46\108\117\97'))()
end)


iv.Name = "iv"
iv.Parent = Ivadmin
iv.Active = true
iv.AnchorPoint = Vector2.new(0.5, 0.5)
iv.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
iv.BackgroundTransparency = 1.000
iv.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
iv.Selectable = true
iv.Size = UDim2.new(1, 0, 1, 0)
iv.ZIndex = 3
iv.Image = "rbxassetid://3570695787"
iv.ImageColor3 = Color3.fromRGB(66, 66, 66)
iv.ScaleType = Enum.ScaleType.Slice
iv.SliceCenter = Rect.new(100, 100, 100, 100)
iv.SliceScale = 0.120

InfYield.Name = "InfYield"
InfYield.Parent = ScriptsFrame
InfYield.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InfYield.BackgroundTransparency = 1.000
InfYield.BorderSizePixel = 0
InfYield.Position = UDim2.new(0.297934622, 0, 0.605394721, 0)
InfYield.Size = UDim2.new(0, 162, 0, 47)
InfYield.ZIndex = 4
InfYield.Font = Enum.Font.Gotham
InfYield.Text = "Infinite Yield"
InfYield.TextColor3 = Color3.fromRGB(173, 0, 255)
InfYield.TextSize = 25.000
InfYield.MouseButton1Up:Connect(function()
	loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)

inf.Name = "inf"
inf.Parent = InfYield
inf.Active = true
inf.AnchorPoint = Vector2.new(0.5, 0.5)
inf.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
inf.BackgroundTransparency = 1.000
inf.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
inf.Selectable = true
inf.Size = UDim2.new(1, 0, 1, 0)
inf.ZIndex = 3
inf.Image = "rbxassetid://3570695787"
inf.ImageColor3 = Color3.fromRGB(66, 66, 66)
inf.ScaleType = Enum.ScaleType.Slice
inf.SliceCenter = Rect.new(100, 100, 100, 100)
inf.SliceScale = 0.120

OtherScripts.Name = "OtherScripts"
OtherScripts.Parent = ScrollingFrame
OtherScripts.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
OtherScripts.BackgroundTransparency = 1.000
OtherScripts.BorderSizePixel = 0
OtherScripts.Position = UDim2.new(0.0500000007, 0, 0.346685141, 0)
OtherScripts.Size = UDim2.new(0, 105, 0, 32)
OtherScripts.ZIndex = 2
OtherScripts.Font = Enum.Font.Gotham
OtherScripts.Text = "Other Scripts"
OtherScripts.TextColor3 = Color3.fromRGB(173, 0, 255)
OtherScripts.TextSize = 15.000
OtherScripts.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	ScriptsFrame.Visible = true
end)

scriptround.Name = "scriptround"
scriptround.Parent = OtherScripts
scriptround.Active = true
scriptround.AnchorPoint = Vector2.new(0.5, 0.5)
scriptround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
scriptround.BackgroundTransparency = 1.000
scriptround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
scriptround.Selectable = true
scriptround.Size = UDim2.new(1, 0, 1, 0)
scriptround.Image = "rbxassetid://3570695787"
scriptround.ImageColor3 = Color3.fromRGB(66, 66, 66)
scriptround.ScaleType = Enum.ScaleType.Slice
scriptround.SliceCenter = Rect.new(100, 100, 100, 100)
scriptround.SliceScale = 0.120

AimFrame.Name = "AimFrame"
AimFrame.Parent = Gui
AimFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
AimFrame.BackgroundTransparency = 1.000
AimFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
AimFrame.Size = UDim2.new(0, 490, 0, 304)
AimFrame.Image = "rbxassetid://3570695787"
AimFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
AimFrame.ScaleType = Enum.ScaleType.Slice
AimFrame.SliceCenter = Rect.new(100, 100, 100, 100)
AimFrame.SliceScale = 0.120
AimFrame.Visible = false

aimdisabled.Name = "aimdisabled"
aimdisabled.Parent = AimFrame
aimdisabled.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimdisabled.BackgroundTransparency = 1.000
aimdisabled.BorderSizePixel = 0
aimdisabled.Position = UDim2.new(0.182277381, 0, 0.184342146, 0)
aimdisabled.Size = UDim2.new(0, 106, 0, 33)
aimdisabled.ZIndex = 5
aimdisabled.Font = Enum.Font.Gotham
aimdisabled.Text = "Disabled"
aimdisabled.TextColor3 = Color3.fromRGB(255, 255, 255)
aimdisabled.TextSize = 25.000

aimdisround.Name = "aimdisround"
aimdisround.Parent = aimdisabled
aimdisround.Active = true
aimdisround.AnchorPoint = Vector2.new(0.5, 0.5)
aimdisround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimdisround.BackgroundTransparency = 1.000
aimdisround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
aimdisround.Selectable = true
aimdisround.Size = UDim2.new(1, 0, 1, 0)
aimdisround.ZIndex = 4
aimdisround.Image = "rbxassetid://3570695787"
aimdisround.ImageColor3 = Color3.fromRGB(255, 0, 0)
aimdisround.ScaleType = Enum.ScaleType.Slice
aimdisround.SliceCenter = Rect.new(100, 100, 100, 100)
aimdisround.SliceScale = 0.120

aimmod.Name = "aimmod"
aimmod.Parent = AimFrame
aimmod.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimmod.BackgroundTransparency = 1.000
aimmod.BorderSizePixel = 0
aimmod.Size = UDim2.new(0, 490, 0, 39)
aimmod.ZIndex = 2
aimmod.Font = Enum.Font.Gotham
aimmod.Text = "Aimbot"
aimmod.TextColor3 = Color3.fromRGB(0, 255, 117)
aimmod.TextSize = 35.000

aimmodround.Name = "aimmodround"
aimmodround.Parent = aimmod
aimmodround.AnchorPoint = Vector2.new(0.5, 0.5)
aimmodround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimmodround.BackgroundTransparency = 1.000
aimmodround.Position = UDim2.new(0.5, 0, 0.5, 0)
aimmodround.Size = UDim2.new(1, 0, 1, 0)
aimmodround.Image = "rbxassetid://3570695787"
aimmodround.ImageColor3 = Color3.fromRGB(66, 66, 66)
aimmodround.ScaleType = Enum.ScaleType.Slice
aimmodround.SliceCenter = Rect.new(100, 100, 100, 100)
aimmodround.SliceScale = 0.120

aimok.Name = "aimok"
aimok.Parent = AimFrame
aimok.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimok.BackgroundTransparency = 1.000
aimok.BorderSizePixel = 0
aimok.Position = UDim2.new(0.0428326055, 0, 0.184342146, 0)
aimok.Size = UDim2.new(0, 48, 0, 34)
aimok.ZIndex = 2
aimok.Font = Enum.Font.Gotham
aimok.Text = "Ok"
aimok.TextColor3 = Color3.fromRGB(0, 255, 117)
aimok.TextSize = 25.000
_G.aimtoggled = false
local camera = game.Workspace.CurrentCamera
local player = game.Players.LocalPlayer
local mouse = player:GetMouse()


_G.aim = false

function closestPlayer()
	local closestplayer = nil
	local closestdist = math.huge
	for i,v in pairs(game.Players:GetPlayers()) do
		if v ~= player and v.Team ~= player.Team then
			local dist = (player.Character.HumanoidRootPart.Position - v.Character.HumanoidRootPart.Position).magnitude
			if dist < closestdist then
				closestdist = dist
				closestplayer = v
			end

		end
	end
	return closestplayer
end


aimok.MouseButton1Up:Connect(function()
	_G.aimtoggled = not _G.aimtoggled
	if _G.aimtoggled then
		aimdisabled.Text = "Enabled"
		aimdisround.ImageColor3 = Color3.fromRGB(0,255,0)
		local UserInputService = game:GetService("UserInputService")
		UserInputService.InputBegan:Connect(function(inputObject)
			if inputObject.UserInputType == Enum.UserInputType.MouseButton1 and _G.aimtoggled then
				_G.aim = true
				print(_G.aim)
				while _G.aim == true do
					camera.CFrame = CFrame.new(camera.CFrame.Position,closestPlayer().Character.Head.Position)
					wait(0.001)
				end
			end
		end)

		UserInputService.InputEnded:Connect(function(inputObject)
			if inputObject.UserInputType == Enum.UserInputType.MouseButton1 and _G.aimtoggled then
				_G.aim = false

				print(_G.aim)
			end
		end)
	end

	if _G.aimtoggled == false then
		aimdisabled.Text = "Disabled"
		aimdisround.ImageColor3 = Color3.fromRGB(255,0,0)
		_G.aim = false
	end
end)

aimokround.Name = "aimokround"
aimokround.Parent = aimok
aimokround.Active = true
aimokround.AnchorPoint = Vector2.new(0.5, 0.5)
aimokround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimokround.BackgroundTransparency = 1.000
aimokround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
aimokround.Selectable = true
aimokround.Size = UDim2.new(1, 0, 1, 0)
aimokround.Image = "rbxassetid://3570695787"
aimokround.ImageColor3 = Color3.fromRGB(66, 66, 66)
aimokround.ScaleType = Enum.ScaleType.Slice
aimokround.SliceCenter = Rect.new(100, 100, 100, 100)
aimokround.SliceScale = 0.120

AimBot.Name = "AimBot"
AimBot.Parent = ScrollingFrame
AimBot.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
AimBot.BackgroundTransparency = 1.000
AimBot.BorderSizePixel = 0
AimBot.Position = UDim2.new(0.0500000007, 0, 0.400083184, 0)
AimBot.Size = UDim2.new(0, 105, 0, 32)
AimBot.ZIndex = 2
AimBot.Font = Enum.Font.Gotham
AimBot.Text = "Aimbot"
AimBot.TextColor3 = Color3.fromRGB(0, 255, 117)
AimBot.TextSize = 18.000
AimBot.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end

	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	AimFrame.Visible = true
end)

aimround.Name = "aimround"
aimround.Parent = AimBot
aimround.Active = true
aimround.AnchorPoint = Vector2.new(0.5, 0.5)
aimround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
aimround.BackgroundTransparency = 1.000
aimround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
aimround.Selectable = true
aimround.Size = UDim2.new(1, 0, 1, 0)
aimround.Image = "rbxassetid://3570695787"
aimround.ImageColor3 = Color3.fromRGB(66, 66, 66)
aimround.ScaleType = Enum.ScaleType.Slice
aimround.SliceCenter = Rect.new(100, 100, 100, 100)
aimround.SliceScale = 0.120

SpectateFrame.Name = "SpectateFrame"
SpectateFrame.Parent = Gui
SpectateFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SpectateFrame.BackgroundTransparency = 1.000
SpectateFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
SpectateFrame.Size = UDim2.new(0, 490, 0, 304)
SpectateFrame.Image = "rbxassetid://3570695787"
SpectateFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
SpectateFrame.ScaleType = Enum.ScaleType.Slice
SpectateFrame.SliceCenter = Rect.new(100, 100, 100, 100)
SpectateFrame.SliceScale = 0.120
SpectateFrame.Visible = false

specdisable.Name = "specdisable"
specdisable.Parent = SpectateFrame
specdisable.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specdisable.BackgroundTransparency = 1.000
specdisable.BorderSizePixel = 0
specdisable.Position = UDim2.new(0.170032486, 0, 0.457368463, 0)
specdisable.Size = UDim2.new(0, 106, 0, 33)
specdisable.ZIndex = 4
specdisable.Font = Enum.Font.Gotham
specdisable.Text = "Disabled"
specdisable.TextColor3 = Color3.fromRGB(255, 255, 255)
specdisable.TextSize = 25.000

specdisableround.Name = "specdisableround"
specdisableround.Parent = specdisable
specdisableround.Active = true
specdisableround.AnchorPoint = Vector2.new(0.5, 0.5)
specdisableround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specdisableround.BackgroundTransparency = 1.000
specdisableround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
specdisableround.Selectable = true
specdisableround.Size = UDim2.new(1, 0, 1, 0)
specdisableround.ZIndex = 3
specdisableround.Image = "rbxassetid://3570695787"
specdisableround.ImageColor3 = Color3.fromRGB(255, 0, 0)
specdisableround.ScaleType = Enum.ScaleType.Slice
specdisableround.SliceCenter = Rect.new(100, 100, 100, 100)
specdisableround.SliceScale = 0.120

SpecMod.Name = "SpecMod"
SpecMod.Parent = SpectateFrame
SpecMod.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SpecMod.BackgroundTransparency = 1.000
SpecMod.BorderSizePixel = 0
SpecMod.Size = UDim2.new(0, 490, 0, 39)
SpecMod.ZIndex = 2
SpecMod.Font = Enum.Font.Gotham
SpecMod.Text = "Spectate Players"
SpecMod.TextColor3 = Color3.fromRGB(112, 0, 255)
SpecMod.TextSize = 35.000

specmodorund.Name = "specmodorund"
specmodorund.Parent = SpecMod
specmodorund.AnchorPoint = Vector2.new(0.5, 0.5)
specmodorund.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specmodorund.BackgroundTransparency = 1.000
specmodorund.Position = UDim2.new(0.5, 0, 0.5, 0)
specmodorund.Size = UDim2.new(1, 0, 1, 0)
specmodorund.Image = "rbxassetid://3570695787"
specmodorund.ImageColor3 = Color3.fromRGB(66, 66, 66)
specmodorund.ScaleType = Enum.ScaleType.Slice
specmodorund.SliceCenter = Rect.new(100, 100, 100, 100)
specmodorund.SliceScale = 0.120

specplayerbox.Name = "specplayerbox"
specplayerbox.Parent = SpectateFrame
specplayerbox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specplayerbox.BackgroundTransparency = 1.000
specplayerbox.BorderSizePixel = 0
specplayerbox.Position = UDim2.new(0.0285714287, 0, 0.319999993, 0)
specplayerbox.Size = UDim2.new(0, 172, 0, 39)
specplayerbox.ZIndex = 2
specplayerbox.Font = Enum.Font.Gotham
specplayerbox.Text = ""
specplayerbox.TextColor3 = Color3.fromRGB(255, 255, 255)
specplayerbox.TextSize = 14.000

specplayerboxround.Name = "specplayerboxround"
specplayerboxround.Parent = specplayerbox
specplayerboxround.Active = true
specplayerboxround.AnchorPoint = Vector2.new(0.5, 0.5)
specplayerboxround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specplayerboxround.BackgroundTransparency = 1.000
specplayerboxround.Position = UDim2.new(0.5057441, 0, 0.4830513, 0)
specplayerboxround.Selectable = true
specplayerboxround.Size = UDim2.new(1, 0, 1, 0)
specplayerboxround.Image = "rbxassetid://3570695787"
specplayerboxround.ImageColor3 = Color3.fromRGB(84, 84, 84)
specplayerboxround.ScaleType = Enum.ScaleType.Slice
specplayerboxround.SliceCenter = Rect.new(100, 100, 100, 100)
specplayerboxround.SliceScale = 0.120

somthspec.Name = "somthspec"
somthspec.Parent = SpectateFrame
somthspec.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
somthspec.BackgroundTransparency = 1.000
somthspec.Position = UDim2.new(-2.45403498e-05, 0, 0.13763158, 0)
somthspec.Size = UDim2.new(0, 217, 0, 54)
somthspec.Font = Enum.Font.Gotham
somthspec.Text = "Enter a players username( not display name)"
somthspec.TextColor3 = Color3.fromRGB(112, 0, 255)
somthspec.TextSize = 17.000
somthspec.TextWrapped = true

specok.Name = "specok"
specok.Parent = SpectateFrame
specok.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specok.BackgroundTransparency = 1.000
specok.BorderSizePixel = 0
specok.Position = UDim2.new(0.0305877067, 0, 0.457368463, 0)
specok.Size = UDim2.new(0, 48, 0, 34)
specok.ZIndex = 2
specok.Font = Enum.Font.Gotham
specok.Text = "Ok"
specok.TextColor3 = Color3.fromRGB(112, 0, 255)
specok.TextSize = 25.000
camera = game.Workspace.CurrentCamera
specok.MouseButton1Up:Connect(function()
	camera.CameraSubject = game.Players[specplayerbox.Text].Character.Humanoid
end)

specokround.Name = "specokround"
specokround.Parent = specok
specokround.Active = true
specokround.AnchorPoint = Vector2.new(0.5, 0.5)
specokround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specokround.BackgroundTransparency = 1.000
specokround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
specokround.Selectable = true
specokround.Size = UDim2.new(1, 0, 1, 0)
specokround.Image = "rbxassetid://3570695787"
specokround.ImageColor3 = Color3.fromRGB(66, 66, 66)
specokround.ScaleType = Enum.ScaleType.Slice
specokround.SliceCenter = Rect.new(100, 100, 100, 100)
specokround.SliceScale = 0.120

Spectate.Name = "Spectate"
Spectate.Parent = ScrollingFrame
Spectate.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Spectate.BackgroundTransparency = 1.000
Spectate.BorderSizePixel = 0
Spectate.Position = UDim2.new(0.0500000007, 0, 0.454694837, 0)
Spectate.Size = UDim2.new(0, 105, 0, 32)
Spectate.ZIndex = 2
Spectate.Font = Enum.Font.Gotham
Spectate.Text = "Spectate"
Spectate.TextColor3 = Color3.fromRGB(112, 0, 255)
Spectate.TextSize = 18.000
Spectate.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end

	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if AnimationsFrame.Visible == true then
		AnimationsFrame.Visible = false
	end
	SpectateFrame.Visible = true
end)

specround.Name = "specround"
specround.Parent = Spectate
specround.Active = true
specround.AnchorPoint = Vector2.new(0.5, 0.5)
specround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
specround.BackgroundTransparency = 1.000
specround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
specround.Selectable = true
specround.Size = UDim2.new(1, 0, 1, 0)
specround.Image = "rbxassetid://3570695787"
specround.ImageColor3 = Color3.fromRGB(66, 66, 66)
specround.ScaleType = Enum.ScaleType.Slice
specround.SliceCenter = Rect.new(100, 100, 100, 100)
specround.SliceScale = 0.120
hub.Name = "hub"
hub.Parent = Gui
hub.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
hub.BackgroundTransparency = 1.000
hub.BorderSizePixel = 0
hub.Position = UDim2.new(0.312, 0,0.036, 0)
hub.Size = UDim2.new(0, 84,0, 35)
hub.ZIndex = 2
hub.Font = Enum.Font.GothamBold
hub.Text = "hub"
hub.TextColor3 = Color3.fromRGB(0, 0, 0)
hub.TextScaled = true
hub.TextSize = 14.000
hub.TextWrapped = true

hubround.Name = "hubround"
hubround.Parent = hub
hubround.AnchorPoint = Vector2.new(0.5, 0.5)
hubround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
hubround.BackgroundTransparency = 1.000
hubround.Position = UDim2.new(0.5, 0, 0.5, 0)
hubround.Size = UDim2.new(1, 0, 1, 0)
hubround.Image = "rbxassetid://3570695787"
hubround.ImageColor3 = Color3.fromRGB(255, 121, 25)
hubround.ScaleType = Enum.ScaleType.Slice
hubround.SliceCenter = Rect.new(100, 100, 100, 100)
hubround.SliceScale = 0.120

Animations.Name = "Animations"
Animations.Parent = ScrollingFrame
Animations.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Animations.BackgroundTransparency = 1.000
Animations.BorderSizePixel = 0
Animations.Position = UDim2.new(0.0422480628, 0, 0.50566572, 0)
Animations.Size = UDim2.new(0, 105, 0, 32)
Animations.ZIndex = 2
Animations.Font = Enum.Font.Gotham
Animations.Text = "Animations"
Animations.TextColor3 = Color3.fromRGB(81, 0, 255)
Animations.TextSize = 18.000
Animations.MouseButton1Up:Connect(function()
	if HighJumpFrame.Visible == true then
		HighJumpFrame.Visible = false
	end
	if GameTPFrame.Visible == true then
		GameTPFrame.Visible = false
	end
	if SpeedFrame.Visible == true then
		SpeedFrame.Visible = false
	end
	if InfJumpFrame.Visible == true then
		InfJumpFrame.Visible = false
	end
	if InvisibilityFrame.Visible == true then
		InvisibilityFrame.Visible = false
	end
	if EspFrame.Visible == true then
		EspFrame.Visible = false
	end

	if ScriptsFrame.Visible == true then
		ScriptsFrame.Visible = false
	end
	if AimFrame.Visible == true then
		AimFrame.Visible = false
	end
	if SpectateFrame.Visible == true then
		SpectateFrame.Visible = false
	end
	AnimationsFrame.Visible = true

end)

animround.Name = "animround"
animround.Parent = Animations
animround.Active = true
animround.AnchorPoint = Vector2.new(0.5, 0.5)
animround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
animround.BackgroundTransparency = 1.000
animround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
animround.Selectable = true
animround.Size = UDim2.new(1, 0, 1, 0)
animround.Image = "rbxassetid://3570695787"
animround.ImageColor3 = Color3.fromRGB(66, 66, 66)
animround.ScaleType = Enum.ScaleType.Slice
animround.SliceCenter = Rect.new(100, 100, 100, 100)
animround.SliceScale = 0.120
Animations_2.Name = "Animations"
Animations_2.Parent = AnimationsFrame
Animations_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Animations_2.BackgroundTransparency = 1.000
Animations_2.BorderSizePixel = 0
Animations_2.Size = UDim2.new(0, 490, 0, 39)
Animations_2.ZIndex = 4
Animations_2.Font = Enum.Font.Gotham
Animations_2.Text = "Animations"
Animations_2.TextColor3 = Color3.fromRGB(81, 0, 255)
Animations_2.TextSize = 35.000
AnimationsFrame.Name = "Animations Frame"
AnimationsFrame.Parent = Gui
AnimationsFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
AnimationsFrame.BackgroundTransparency = 1.000
AnimationsFrame.Position = UDim2.new(0.249275357, 0, 0.193877548, 0)
AnimationsFrame.Size = UDim2.new(0, 490, 0, 304)
AnimationsFrame.ZIndex = 3
AnimationsFrame.Image = "rbxassetid://3570695787"
AnimationsFrame.ImageColor3 = Color3.fromRGB(109, 109, 109)
AnimationsFrame.ScaleType = Enum.ScaleType.Slice
AnimationsFrame.SliceCenter = Rect.new(100, 100, 100, 100)
AnimationsFrame.SliceScale = 0.120
AnimationsFrame.Visible = false

othscrround.Name = "othscrround"
othscrround.Parent = Animations_2
othscrround.AnchorPoint = Vector2.new(0.5, 0.5)
othscrround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
othscrround.BackgroundTransparency = 1.000
othscrround.Position = UDim2.new(0.5, 0, 0.5, 0)
othscrround.Size = UDim2.new(1, 0, 1, 0)
othscrround.ZIndex = 3
othscrround.Image = "rbxassetid://3570695787"
othscrround.ImageColor3 = Color3.fromRGB(66, 66, 66)
othscrround.ScaleType = Enum.ScaleType.Slice
othscrround.SliceCenter = Rect.new(100, 100, 100, 100)
othscrround.SliceScale = 0.120

Float.Name = "Float"
Float.Parent = AnimationsFrame
Float.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Float.BackgroundTransparency = 1.000
Float.BorderSizePixel = 0
Float.Position = UDim2.new(0.0489550531, 0, 0.187631607, 0)
Float.Size = UDim2.new(0, 162, 0, 47)
Float.ZIndex = 4
Float.Font = Enum.Font.Gotham
Float.Text = "Float"
Float.TextColor3 = Color3.fromRGB(81, 0, 255)
Float.TextSize = 25.000
_G.float = false
Float.MouseButton1Up:Connect(function()
	_G.float = not _G.float
	if _G.float then
		local player = game.Players.LocalPlayer
		local mouse = player:GetMouse()
		player.Character.Humanoid.HipHeight = 4
		game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded Float"; Duration=4;})
		while _G.float do
			player.Character.Humanoid:ChangeState(Enum.HumanoidStateType.Freefall)
			wait()
		end

	else
		player.Character.Humanoid.HipHeight = 1
	end
	
end)


floatround.Name = "floatround"
floatround.Parent = Float
floatround.Active = true
floatround.AnchorPoint = Vector2.new(0.5, 0.5)
floatround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
floatround.BackgroundTransparency = 1.000
floatround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
floatround.Selectable = true
floatround.Size = UDim2.new(1, 0, 1, 0)
floatround.ZIndex = 3
floatround.Image = "rbxassetid://3570695787"
floatround.ImageColor3 = Color3.fromRGB(66, 66, 66)
floatround.ScaleType = Enum.ScaleType.Slice
floatround.SliceCenter = Rect.new(100, 100, 100, 100)
floatround.SliceScale = 0.120

anim3.Name = "anim3"
anim3.Parent = AnimationsFrame
anim3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
anim3.BackgroundTransparency = 1.000
anim3.BorderSizePixel = 0
anim3.Position = UDim2.new(0.0489550233, 0, 0.671184242, 0)
anim3.Size = UDim2.new(0, 162, 0, 47)
anim3.ZIndex = 4
anim3.Font = Enum.Font.Gotham
anim3.Text = "Jiggly Boobas"
anim3.TextColor3 = Color3.fromRGB(81, 0, 255)
anim3.TextSize = 25.000
anim3.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer
	local mouse  = player:GetMouse()
	local hat1   = player.Character["Pal Hair"].Handle
	local hat2   = player.Character["Robloxclassicred"].Handle
	hat1.AccessoryWeld:Destroy()
	hat1.Mesh:Destroy()
	hat2.AccessoryWeld:Destroy()
	hat2.Mesh:Destroy()
	game:GetService("RunService").Heartbeat:Connect(function()
		hat1.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(0.6,0.4,-0.6)
		hat2.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(-0.6,0.4,-0.6)
	end)
	game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded Jiggly Bobas"; Duration=4;})
end)
anim3round.Name = "anim3round"
anim3round.Parent = anim3
anim3round.Active = true
anim3round.AnchorPoint = Vector2.new(0.5, 0.5)
anim3round.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
anim3round.BackgroundTransparency = 1.000
anim3round.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
anim3round.Selectable = true
anim3round.Size = UDim2.new(1, 0, 1, 0)
anim3round.ZIndex = 3
anim3round.Image = "rbxassetid://3570695787"
anim3round.ImageColor3 = Color3.fromRGB(66, 66, 66)
anim3round.ScaleType = Enum.ScaleType.Slice
anim3round.SliceCenter = Rect.new(100, 100, 100, 100)
anim3round.SliceScale = 0.120

BigPP.Name = "BigPP"
BigPP.Parent = AnimationsFrame
BigPP.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
BigPP.BackgroundTransparency = 1.000
BigPP.BorderSizePixel = 0
BigPP.Position = UDim2.new(0.0489550233, 0, 0.421184182, 0)
BigPP.Size = UDim2.new(0, 162, 0, 47)
BigPP.ZIndex = 4
BigPP.Font = Enum.Font.Gotham
BigPP.Text = "Big PP"
BigPP.TextColor3 = Color3.fromRGB(81, 0, 255)
BigPP.TextSize = 25.000
BigPP.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer
	local mouse  = player:GetMouse()
	local hat    = player.Character["Pal Hair"].Handle
	hat.AccessoryWeld:Destroy()
	hat.Mesh:Destroy()
	game:GetService("RunService").Heartbeat:Connect(function()
		hat.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(0,-1.2,-1.5)
	end)
	game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded Big PP"; Duration=4;})
end)

pp.Name = "pp"
pp.Parent = BigPP
pp.Active = true
pp.AnchorPoint = Vector2.new(0.5, 0.5)
pp.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
pp.BackgroundTransparency = 1.000
pp.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
pp.Selectable = true
pp.Size = UDim2.new(1, 0, 1, 0)
pp.ZIndex = 3
pp.Image = "rbxassetid://3570695787"
pp.ImageColor3 = Color3.fromRGB(66, 66, 66)
pp.ScaleType = Enum.ScaleType.Slice
pp.SliceCenter = Rect.new(100, 100, 100, 100)
pp.SliceScale = 0.120

local tpose = Instance.new("TextButton")
local tposeround = Instance.new("ImageLabel")

tpose.Name = "tpose"
tpose.Parent = AnimationsFrame
tpose.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
tpose.BackgroundTransparency = 1.000
tpose.BorderSizePixel = 0
tpose.Position = UDim2.new(0.5958938, 0, 0.184342146, 0)
tpose.Size = UDim2.new(0, 162, 0, 47)
tpose.ZIndex = 4
tpose.Font = Enum.Font.Gotham
tpose.Text = "T-Pose"
tpose.TextColor3 = Color3.fromRGB(81, 0, 255)
tpose.TextSize = 25.000
tpose.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer

	player.Character.Torso["Left Shoulder"]:Destroy()
	player.Character.Torso["Right Shoulder"]:Destroy()
	local leftarm = player.Character["Left Arm"]
	local rightarm = player.Character["Right Arm"]
	game:GetService("RunService").Heartbeat:Connect(function()
		leftarm.CFrame  = player.Character.HumanoidRootPart.CFrame * CFrame.new(-2,.5,0) * CFrame.Angles(0,0,math.rad(90))
		rightarm.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(2,.5,0) * CFrame.Angles(0,0,math.rad(-90))
	end)
	game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded T-Pose"; Duration=4;})
end)

tposeround.Name = "tposeround"
tposeround.Parent = tpose
tposeround.Active = true
tposeround.AnchorPoint = Vector2.new(0.5, 0.5)
tposeround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
tposeround.BackgroundTransparency = 1.000
tposeround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
tposeround.Selectable = true
tposeround.Size = UDim2.new(1, 0, 1, 0)
tposeround.ZIndex = 3
tposeround.Image = "rbxassetid://3570695787"
tposeround.ImageColor3 = Color3.fromRGB(66, 66, 66)
tposeround.ScaleType = Enum.ScaleType.Slice
tposeround.SliceCenter = Rect.new(100, 100, 100, 100)
tposeround.SliceScale = 0.120

local nazi = Instance.new("TextButton")
local naziround = Instance.new("ImageLabel")

nazi.Name = "nazi"
nazi.Parent = AnimationsFrame
nazi.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
nazi.BackgroundTransparency = 1.000
nazi.BorderSizePixel = 0
nazi.Position = UDim2.new(0.593852997, 0, 0.417894781, 0)
nazi.Size = UDim2.new(0, 162, 0, 47)
nazi.ZIndex = 4
nazi.Font = Enum.Font.Gotham
nazi.Text = "Nazi"
nazi.TextColor3 = Color3.fromRGB(81, 0, 255)
nazi.TextSize = 25.000
nazi.MouseButton1Up:Connect(function()
	local player = game.Players.LocalPlayer
	player.Character.Torso["Right Shoulder"]:Destroy()
	local rightarm = player.Character["Right Arm"]
	game:GetService("RunService").Heartbeat:Connect(function()
		rightarm.CFrame = player.Character.HumanoidRootPart.CFrame * CFrame.new(1.5,1,-0.7) * CFrame.Angles(0,math.rad(75),math.rad(125))
	end)
	game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded Nazi"; Duration=4;})
end)

naziround.Name = "naziround"
naziround.Parent = nazi
naziround.Active = true
naziround.AnchorPoint = Vector2.new(0.5, 0.5)
naziround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
naziround.BackgroundTransparency = 1.000
naziround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
naziround.Selectable = true
naziround.Size = UDim2.new(1, 0, 1, 0)
naziround.ZIndex = 3
naziround.Image = "rbxassetid://3570695787"
naziround.ImageColor3 = Color3.fromRGB(66, 66, 66)
naziround.ScaleType = Enum.ScaleType.Slice
naziround.SliceCenter = Rect.new(100, 100, 100, 100)
naziround.SliceScale = 0.120

local Face = Instance.new("TextButton")
local Faceround = Instance.new("ImageLabel")

Face.Name = "Face"
Face.Parent = AnimationsFrame
Face.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Face.BackgroundTransparency = 1.000
Face.BorderSizePixel = 0
Face.Position = UDim2.new(0.5958938, 0, 0.667894781, 0)
Face.Size = UDim2.new(0, 162, 0, 47)
Face.ZIndex = 4
Face.Font = Enum.Font.Gotham
Face.Text = "Bruh Face"
Face.TextColor3 = Color3.fromRGB(255, 0, 153)
Face.TextSize = 25.000
Face.MouseButton1Up:Connect(function()
	local player  = game.Players.LocalPlayer
	local root    = player.Character.HumanoidRootPart

	local hat1 = player.Character["Robloxclassicred"].Handle
	local hat2 = player.Character["Necklace"].Handle
	local hat3 = player.Character["rol_icebrainAccessory"].Handle
	local hat4 = player.Character["Pal Hair"].Handle
	local hat5 = player.Character["BoySpaceHair"].Handle
	hat3.AccessoryWeld:Destroy()
	hat3.SpecialMesh:Destroy()
	local hats = {hat1,hat2,hat4,hat5}

	for i, hat in ipairs(hats) do
		hat.AccessoryWeld:Destroy()
		hat.Mesh:Destroy()
	end
	local sad    = false
	local normal = false
	local mouse  = player:GetMouse()
	mouse.KeyDown:Connect(function(key)
		if key == "r" then 
			sad = not sad
		end

		if key == "q" then 
			normal = not normal
		end
	end)
	game:GetService("RunService").Heartbeat:Connect(function()
		local hat4happy = root.CFrame * CFrame.new(1.6,5,0) * CFrame.Angles(math.rad(-90),math.rad(-120),math.rad(-90))
		local hat2happy = root.CFrame * CFrame.new(-1.6,5,0) * CFrame.Angles(math.rad(90),math.rad(-120),math.rad(90))
		local hat4sad   = root.CFrame * CFrame.new(1.5,4.1,0) * CFrame.Angles(math.rad(-90),math.rad(120),math.rad(-90))
		local hat2sad   = root.CFrame * CFrame.new(-1.5,4.1,0) * CFrame.Angles(math.rad(90),math.rad(120),math.rad(90))
		local hat4bruh  = root.CFrame * CFrame.new(2,4.5,0) * CFrame.Angles(0,math.rad(90),0)
		local hat2bruh  = root.CFrame * CFrame.new(-2,4.5,0) * CFrame.Angles(0,math.rad(90),0)
		hat1.CFrame = root.CFrame * CFrame.new(0,4.5,0) * CFrame.Angles(0,math.rad(90),0)
		hat3.CFrame = root.CFrame * CFrame.new(1,7,0) * CFrame.Angles(0,0,0)
		hat5.CFrame = root.CFrame * CFrame.new(-1,7,0) * CFrame.Angles(0,0,0)
		if sad == true then   
			hat4.CFrame = hat4sad
			hat2.CFrame = hat2sad
		end 
		if sad == false then
			hat4.CFrame = hat4happy
			hat2.CFrame = hat2happy
		end
		if normal then
			hat4.CFrame = hat4bruh
			hat2.CFrame = hat2bruh
		end

	end)
	game.StarterGui:SetCore("SendNotification", {Title="Loaded!"; Text="Succsesfully loaded Bruh Face"; Duration=4;})
end)

Faceround.Name = "Faceround"
Faceround.Parent = Face
Faceround.Active = true
Faceround.AnchorPoint = Vector2.new(0.5, 0.5)
Faceround.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Faceround.BackgroundTransparency = 1.000
Faceround.Position = UDim2.new(0.495238125, 0, 0.497250021, 0)
Faceround.Selectable = true
Faceround.Size = UDim2.new(1, 0, 1, 0)
Faceround.ZIndex = 3
Faceround.Image = "rbxassetid://3570695787"
Faceround.ImageColor3 = Color3.fromRGB(66, 66, 66)
Faceround.ScaleType = Enum.ScaleType.Slice
Faceround.SliceCenter = Rect.new(100, 100, 100, 100)
Faceround.SliceScale = 0.120

function zigzag(X) return math.acos(math.cos(X*math.pi))/math.pi end

counter = 0

while wait(0.1) do
	TextLabel.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Speed.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	HighJump.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	InfJump.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	SpeedModification.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	HighJumpModification.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	InfJumpModification.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Ok.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	OkInfJump.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Ok_2.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	somethigninf.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	somethignjump.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	somethignspeed.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Jailbreak.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	AdoptMe.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Prisonlife.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Plsdonate.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	GameTeleport.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Title.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	madeby.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Invisibility.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	invisok.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	InvisibilityMod.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Esp.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	espok.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	espmod.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	GameChecker.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	OtherScripts.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	othscriptitle.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Ivadmin.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	InfYield.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	OwlHub.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	AimBot.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	aimmod.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	aimok.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	specok.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	SpecMod.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	somthspec.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Spectate.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	teamcheck.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	hubround.ImageColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Animations.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Animations_2.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Float.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	BigPP.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	anim3.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	tpose.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	nazi.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	Face.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	okcode.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	codelabel1.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)
	codelabel2.TextColor3 = Color3.fromHSV(zigzag(counter),1,1)

	counter = counter + 0.01
end
